// Generated by perch from menubar.yaml. Regenerating overwrites this file.

import Foundation

struct AgentResult {
    var ok = false
    var code = -1
    var out = ""
    var err = ""
}

struct PlistResult {
    var ok = false
}

struct Results {
    var agent = AgentResult()
    var plist = PlistResult()
}

extension AgentResult {
    init(_ o: RunOutcome) {
        self.init()
        ok = o.ok
        code = o.code
        out = o.out
        err = o.err
    }
}

extension PlistResult {
    init(exists: Bool) {
        self.init()
        ok = exists
    }
}

extension Results {
    var state_uninstalled: Bool { (!(plist.ok)) }
    var state_stopped: Bool { !state_uninstalled && (!(agent.ok)) }
    var state_running: Bool { !state_uninstalled && !state_stopped }
}

func renderFace(_ results: Results) -> Face {
    var face = Face(icon: MenuIcon.symbol("gearshape"))
    if results.state_uninstalled {
        face.icon = MenuIcon.symbol("exclamationmark.triangle")
    } else if results.state_stopped {
        face.dim = true
    }
    return face
}

func renderMenu(_ results: Results) -> [MenuNode] {
    var menu: [MenuNode] = []
    if results.state_running {
        menu.append(.item("the agent is running", nil))
    }
    if (results.state_uninstalled || results.state_stopped) {
        menu.append(.item("needs attention", nil))
    }
    if (results.agent.out == "uninstalled") {
        menu.append(.item("uninstalled is a word here, not a state", nil))
    }
    menu.append(.item("Quit", .quit))
    return tidy(menu)
}
