// Generated by perch from menubar.yaml. Regenerating overwrites this file.

import AppKit
import Foundation

final class Controller: NSObject, NSApplicationDelegate, NSMenuDelegate {
    private let statusItem = NSStatusBar.system.statusItem(withLength: NSStatusItem.variableLength)
    fileprivate var results = Results()
    private var timer: Timer?
    private var menuOpen = false

    override init() {
        super.init()
        let menu = NSMenu()
        menu.delegate = self
        statusItem.menu = menu
        StatusButton.follow({ [weak menu] in menu }) { [weak self] open in
            self?.menuOpen = open
            self?.refresh()
        }
        refresh()
        poll()
        timer = Timer.scheduledTimer(withTimeInterval: 5.0, repeats: true) { [weak self] _ in
            self?.poll()
        }
    }

    fileprivate func poll() {
        let group = DispatchGroup()
        let sync = DispatchQueue(label: "dev.example.w.results")
        var next = Results()

        group.enter()
        DispatchQueue.global(qos: .utility).async {
            let r = FleetResult(Watcher.run(["onto", "top", "--json"]))
            sync.async {
                next.fleet = r
                group.leave()
            }
        }

        group.notify(queue: .main) { [weak self] in
            guard let self else { return }
            self.results = sync.sync { next }
            self.refresh()
            if let menu = self.statusItem.menu, menu.numberOfItems > 0 { self.menuNeedsUpdate(menu) }
        }
    }

    func refresh() {
        guard let button = statusItem.button else { return }
        Draw.face(renderFace(results), on: button, menuOpen: menuOpen)
    }

    func menuNeedsUpdate(_ menu: NSMenu) {
        Draw.menu(renderMenu(results), into: menu) { [weak self] in self?.poll() }
    }
}

let app = NSApplication.shared
app.setActivationPolicy(.accessory)
let controller = Controller()
app.delegate = controller
app.run()
