// Generated by perch from menubar.yaml. Regenerating overwrites this file.

import Foundation

struct FleetResult {
    var ok = false
    var code = -1
    var out = ""
    var err = ""
    var data: FleetData = FleetData()
}

struct Results {
    var fleet = FleetResult()
}

extension FleetResult {
    init(_ o: RunOutcome) {
        self.init()
        ok = o.ok
        code = o.code
        out = o.out
        err = o.err
        data = (try? JSONDecoder().decode(FleetData.self, from: Data(o.out.utf8))) ?? FleetData()
    }
}

func renderFace(_ results: Results) -> Face {
    let face = Face(icon: MenuIcon.symbol("gear"))
    return face
}

func renderMenu(_ results: Results) -> [MenuNode] {
    var menu: [MenuNode] = []
    menu.append(.field("Search GitHub", { query1 in .open("https://github.com/search?q=\(Act.urlQuery(query1))") }))
    menu.append(.field("Find job", { query2 in .run(["onto", "find", "\(query2)"]) }))
    for it3 in results.fleet.data.jobs {
        menu.append(.field("Grep \(it3.node)", { query4 in .post(url: "http://localhost/\(it3.id)", body: "{\"q\":\"\(Act.jsonEscaped(query4))\"}") }))
    }
    menu.append(.item("Quit", .quit))
    return tidy(menu)
}
