// Generated by perch from menubar.yaml. Regenerating overwrites this file.

import Foundation

struct FleetData: Decodable {
    var jobs: [FleetDataJobs] = []

    init() {}

    private enum CodingKeys: String, CodingKey {
        case jobs
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.jobs = (try? c.decode([FleetDataJobs].self, forKey: .jobs)) ?? []
    }
}

struct FleetDataJobs: Decodable {
    var id: String = ""
    var node: String = ""

    init() {}

    private enum CodingKeys: String, CodingKey {
        case id
        case node
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.id = (try? c.decode(String.self, forKey: .id)) ?? ""
        self.node = (try? c.decode(String.self, forKey: .node)) ?? ""
    }
}

