// Generated by perch. Regenerating overwrites this file.
//
// A menu item that takes typed text: a field: in menubar.yaml.

import AppKit

/// A menu item that takes typed text. Enter hands the text on and closes the
/// menu; an empty or blank field does nothing.
final class FieldItem: NSMenuItem {
    let field = NSSearchField()
    private let submit: (String) -> Void

    init(placeholder: String, submit: @escaping (String) -> Void) {
        self.submit = submit
        super.init(title: placeholder, action: nil, keyEquivalent: "")
        field.placeholderString = placeholder
        field.sendsWholeSearchString = true
        field.target = self
        field.action = #selector(enter)
        let host = FocusView(frame: NSRect(x: 0, y: 0, width: 240, height: 30))
        field.frame = host.bounds.insetBy(dx: 14, dy: 4)
        field.autoresizingMask = [.width]
        host.addSubview(field)
        host.focus = field
        view = host
    }

    @available(*, unavailable)
    required init(coder: NSCoder) { fatalError("not supported") }

    @objc func enter() {
        let text = field.stringValue
        guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }
        menu?.cancelTracking()
        submit(text)
    }
}

private final class FocusView: NSView {
    weak var focus: NSView?

    override func viewDidMoveToWindow() {
        super.viewDidMoveToWindow()
        guard let window, let focus else { return }
        // The menu's window takes first responder only once tracking has begun.
        DispatchQueue.main.async { window.makeFirstResponder(focus) }
    }
}
