// Generated by perch. Regenerating overwrites this file.
//
// A system-wide shortcut: app.hotkey in menubar.yaml.

import AppKit
import Carbon.HIToolbox

/// A system-wide shortcut, held until it is released. Carbon's hot keys need no
/// Accessibility permission and consume the keystroke, which an NSEvent global
/// monitor does neither of.
final class Hotkey {
    private var ref: EventHotKeyRef?
    private var handler: EventHandlerRef?
    private let fire: () -> Void

    /// nil when the system refuses the combination, as it does one another app
    /// already holds.
    init?(key: Int, modifiers: Int, fire: @escaping () -> Void) {
        self.fire = fire
        var pressed = EventTypeSpec(eventClass: OSType(kEventClassKeyboard), eventKind: UInt32(kEventHotKeyPressed))
        let me = Unmanaged.passUnretained(self).toOpaque()
        let installed = InstallEventHandler(GetApplicationEventTarget(), { _, _, me in
            guard let me else { return OSStatus(eventNotHandledErr) }
            Unmanaged<Hotkey>.fromOpaque(me).takeUnretainedValue().press()
            return noErr
        }, 1, &pressed, me, &handler)
        let id = EventHotKeyID(signature: OSType(0x7065_7263), id: 1) // "perc"
        guard installed == noErr,
              RegisterEventHotKey(UInt32(key), UInt32(modifiers), id, GetApplicationEventTarget(), 0, &ref) == noErr
        else { return nil }
    }

    deinit {
        if let ref { UnregisterEventHotKey(ref) }
        if let handler { RemoveEventHandler(handler) }
    }

    func press() { fire() }
}
