// Generated by perch. Regenerating overwrites this file.
//
// The status item's and menu items' icons, and the tint that tells one perch
// app from another in the menu bar. Nothing here depends on menubar.yaml.

import AppKit
import Foundation

// MARK: - MenuIcon

/// What the status item shows. A symbol is drawn as a template, so macOS tints
/// it for the menu bar's own appearance and for whether the bar is selected. An
/// asset is artwork the consuming repo drew, which macOS will not tint and
/// which therefore has to carry its own color.
enum MenuIcon {
    case symbol(String)
    case asset(String)

    func image() -> NSImage? {
        // Measured off the bar rather than fixed at the 18pt a menu bar used
        // to be: the bar has been taller than that for several releases, and
        // artwork sized to the old number sits in the middle of its frame
        // looking like a mistake. The inset is what keeps it off the edges.
        image(assetHeight: max(NSStatusBar.system.thickness - 5, 12))
    }

    /// The status item's image with a tint applied. A tinted image is color,
    /// not a template, so a symbol's own strokes are drawn in the label color
    /// to keep following the bar's appearance.
    func image(tint: Tint?) -> NSImage? {
        guard let tint, let plain = image() else { return image() }
        let colored: NSImage
        switch (self, tint.style) {
        case (.symbol, .glyph):
            return Tint.untemplated(plain.withSymbolConfiguration(.init(hierarchicalColor: tint.color)))
        case (.symbol, .accent):
            return Tint.untemplated(plain.withSymbolConfiguration(.init(paletteColors: [.labelColor, tint.color])))
        case (.asset, .glyph), (.asset, .accent):
            return plain // refused at build: artwork has no layers to recolor
        case (.symbol, _):
            guard let image = plain.withSymbolConfiguration(.init(hierarchicalColor: .labelColor)) else { return plain }
            colored = image
        case (.asset, _):
            colored = plain
        }
        return tint.style == .chip ? tint.chip(colored) : tint.dot(colored)
    }

    /// The same icon beside a menu item, where AppKit's own images are 16pt.
    func menuImage() -> NSImage? {
        image(assetHeight: 16)
    }

    private func image(assetHeight height: CGFloat) -> NSImage? {
        switch self {
        case .symbol(let name):
            let image = NSImage(systemSymbolName: name, accessibilityDescription: nil)
            image?.isTemplate = true
            return image
        case .asset(let name):
            guard let image = MenuIcon.load(name), image.size.height > 0 else { return nil }
            image.size = NSSize(width: height * (image.size.width / image.size.height), height: height)
            return image
        }
    }

    /// How faint to draw, approximating the fade macOS gives a template when the
    /// menu bar goes inactive and gives a colored image not at all. The bar is
    /// taken as inactive when the item's own screen is not the one holding the
    /// active menu bar, which is right for the two common cases — another
    /// display has focus, or a full screen app owns this one — and wrong for
    /// anything else that dims the bar. A template is left alone: it has
    /// already faded, and fading it twice is worse than not matching.
    static func alpha(of image: NSImage?, on button: NSStatusBarButton) -> CGFloat {
        guard let image, !image.isTemplate else { return 1 }
        guard let screen = button.window?.screen, let active = NSScreen.main else { return 1 }
        return screen == active ? 1 : 0.55
    }

    /// `<name>~dark.png` where the bundle carries one. A template gets its two
    /// appearances from macOS; artwork that keeps its own color does not, so an
    /// asset whose outline must read against both menu bars ships both.
    private static func load(_ name: String) -> NSImage? {
        // A templated name is only known now, so the check perch makes at
        // build is made again here: one file in the bundle's Resources.
        let allowed = CharacterSet(charactersIn: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_")
        guard !name.isEmpty, name.unicodeScalars.allSatisfy(allowed.contains) else { return nil }
        let dark = NSApp.effectiveAppearance.bestMatch(from: [.aqua, .darkAqua]) == .darkAqua
        if dark, let path = Bundle.main.path(forResource: name + "~dark", ofType: "png"),
           let image = NSImage(contentsOfFile: path) {
            return image
        }
        guard let path = Bundle.main.path(forResource: name, ofType: "png") else { return nil }
        return NSImage(contentsOfFile: path)
    }
}

// MARK: - Tint

/// A color on the status item. Render.swift decides it as data; this draws it.
struct Tint {
    enum Style: String { case glyph, accent, dot, chip }
    enum Size: String { case small, medium, large }
    enum Corner: String {
        case bottomRight = "bottom-right", bottomLeft = "bottom-left", topRight = "top-right", topLeft = "top-left"
    }

    /// One of the system colors' names, or #rrggbb.
    var name: String
    var alpha: CGFloat
    var style: Style
    var size: Size
    var corner: Corner

    init(color: String, alpha: CGFloat, style: Style, size: Size, corner: Corner) {
        self.name = color
        self.alpha = alpha
        self.style = style
        self.size = size
        self.corner = corner
    }

    /// The system colors are dynamic, so they shift between a light and a dark
    /// menu bar; a hex color is the same on both.
    var color: NSColor {
        let base: NSColor
        if name.hasPrefix("#"), let v = UInt32(name.dropFirst(), radix: 16) {
            base = NSColor(srgbRed: CGFloat(v >> 16 & 0xff) / 255, green: CGFloat(v >> 8 & 0xff) / 255,
                           blue: CGFloat(v & 0xff) / 255, alpha: 1)
        } else {
            switch name {
            case "red": base = .systemRed
            case "orange": base = .systemOrange
            case "yellow": base = .systemYellow
            case "green": base = .systemGreen
            case "mint": base = .systemMint
            case "teal": base = .systemTeal
            case "cyan": base = .systemCyan
            case "blue": base = .systemBlue
            case "indigo": base = .systemIndigo
            case "purple": base = .systemPurple
            case "pink": base = .systemPink
            case "brown": base = .systemBrown
            case "gray": base = .systemGray
            default: base = .labelColor
            }
        }
        return base.withAlphaComponent(alpha)
    }

    var diameter: CGFloat {
        switch size {
        case .small: return 4
        case .medium: return 5
        case .large: return 6
        }
    }

    static func untemplated(_ image: NSImage?) -> NSImage? {
        image?.isTemplate = false
        return image
    }

    /// The icon with a dot on one corner, and a gap cut around the dot so it
    /// reads apart from whatever stroke it lands on.
    func dot(_ icon: NSImage) -> NSImage {
        let size = icon.size, d = diameter, color = color
        let x = corner == .bottomLeft || corner == .topLeft ? 0 : size.width - d
        let y = corner == .bottomLeft || corner == .bottomRight ? 0 : size.height - d
        let spot = NSRect(x: x, y: y, width: d, height: d)
        return Tint.untemplated(NSImage(size: size, flipped: false) { rect in
            icon.draw(in: rect)
            NSGraphicsContext.current?.compositingOperation = .clear
            NSBezierPath(ovalIn: spot.insetBy(dx: -1.5, dy: -1.5)).fill()
            NSGraphicsContext.current?.compositingOperation = .sourceOver
            color.setFill()
            NSBezierPath(ovalIn: spot).fill()
            return true
        })!
    }

    /// The icon on a rounded patch of the color.
    func chip(_ icon: NSImage) -> NSImage {
        let pad = NSSize(width: 4, height: 2), color = color
        let size = NSSize(width: icon.size.width + 2 * pad.width, height: icon.size.height + 2 * pad.height)
        return Tint.untemplated(NSImage(size: size, flipped: false) { rect in
            color.setFill()
            NSBezierPath(roundedRect: rect, xRadius: 4, yRadius: 4).fill()
            icon.draw(in: NSRect(origin: NSPoint(x: pad.width, y: pad.height), size: icon.size))
            return true
        })!
    }
}
