// Generated by perch. Regenerating overwrites this file.
//
// The status item's and menu items' icons, and the tint that tells one perch
// app from another in the menu bar. Nothing here depends on menubar.yaml, and
// the PerchKit library compiles this same file for hand-written apps.

import AppKit
import Foundation

// MARK: - MenuIcon

/// What the status item shows. A symbol is drawn as a template, so macOS tints
/// it for the menu bar's own appearance and for whether the bar is selected. An
/// asset is artwork the consuming repo drew, which macOS will not tint and
/// which therefore has to carry its own color.
enum MenuIcon {
    case symbol(String)
    case asset(String)

    func image() -> NSImage? {
        // Measured off the bar rather than fixed at the 18pt a menu bar used
        // to be: the bar has been taller than that for several releases, and
        // artwork sized to the old number sits in the middle of its frame
        // looking like a mistake. The inset is what keeps it off the edges.
        image(assetHeight: max(NSStatusBar.system.thickness - 5, 12))
    }

    /// The same icon beside a menu item, where AppKit's own images are 16pt.
    func menuImage() -> NSImage? {
        image(assetHeight: 16)
    }

    private func image(assetHeight height: CGFloat) -> NSImage? {
        switch self {
        case .symbol(let name):
            let image = NSImage(systemSymbolName: name, accessibilityDescription: nil)
            image?.isTemplate = true
            return image
        case .asset(let name):
            guard let image = MenuIcon.load(name), image.size.height > 0 else { return nil }
            image.size = NSSize(width: height * (image.size.width / image.size.height), height: height)
            return image
        }
    }

    /// How faint to draw, approximating the fade macOS gives a template when the
    /// menu bar goes inactive and gives a colored image not at all. The bar is
    /// taken as inactive when the item's own screen is not the one holding the
    /// active menu bar, which is right for the two common cases — another
    /// display has focus, or a full screen app owns this one — and wrong for
    /// anything else that dims the bar. A template is left alone: it has
    /// already faded, and fading it twice is worse than not matching.
    static func alpha(of image: NSImage?, on button: NSStatusBarButton) -> CGFloat {
        guard let image, !image.isTemplate else { return 1 }
        guard let screen = button.window?.screen, let active = NSScreen.main else { return 1 }
        return screen == active ? 1 : 0.55
    }

    /// `<name>~dark.png` where the bundle carries one. A template gets its two
    /// appearances from macOS; artwork that keeps its own color does not, so an
    /// asset whose outline must read against both menu bars ships both.
    private static func load(_ name: String) -> NSImage? {
        // A templated name is only known now, so the check perch makes at
        // build is made again here: one file in the bundle's Resources.
        let allowed = CharacterSet(charactersIn: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_")
        guard !name.isEmpty, name.unicodeScalars.allSatisfy(allowed.contains) else { return nil }
        let dark = NSApp.effectiveAppearance.bestMatch(from: [.aqua, .darkAqua]) == .darkAqua
        if dark, let path = Bundle.main.path(forResource: name + "~dark", ofType: "png"),
           let image = NSImage(contentsOfFile: path) {
            return image
        }
        guard let path = Bundle.main.path(forResource: name, ofType: "png") else { return nil }
        return NSImage(contentsOfFile: path)
    }
}

// MARK: - Tint

/// A color on the status item. Render.swift decides it as data; this draws it.
public struct Tint {
    public enum Style: String { case glyph, accent, dot, chip }
    public enum Size: String { case small, medium, large }
    public enum Corner: String {
        case bottomRight = "bottom-right", bottomLeft = "bottom-left", topRight = "top-right", topLeft = "top-left"
    }
    public enum Wrap: String { case icon, all }

    /// How strongly a chip shows a color given without its own alpha. perch's
    /// parser holds the same number for menubar.yaml.
    static let chipAlpha: CGFloat = 0.35

    /// One of the system colors' names, or #rrggbb.
    var name: String
    var alpha: CGFloat
    var style: Style
    var size: Size
    var corner: Corner
    var wrap: Wrap
    var menu: Bool

    init(color: String, alpha: CGFloat, style: Style, size: Size, corner: Corner, wrap: Wrap = .icon, menu: Bool = false) {
        self.name = color
        self.alpha = alpha
        self.style = style
        self.size = size
        self.corner = corner
        self.wrap = wrap
        self.menu = menu
    }

    /// Whether the badge is drawn inside the chip, so the button carries no title.
    var wrapsBadge: Bool { style == .chip && wrap == .all }

    /// Whether a color named at run time is one this can draw: #rrggbb or a
    /// system color. menubar.yaml's colors were checked at build.
    static func draws(_ name: String) -> Bool { base(name) != nil }

    /// The system colors are dynamic, so they shift between a light and a dark
    /// menu bar; a hex color is the same on both.
    var color: NSColor {
        (Tint.base(name) ?? .labelColor).withAlphaComponent(min(max(alpha, 0), 1))
    }

    /// What a chip's icon and badge are drawn in. A patch strong enough to hide
    /// the bar takes the ink that reads on its own color; a fainter one lets
    /// the bar through, so its ink follows the bar.
    var ink: NSColor {
        guard alpha >= Tint.coversBar, let c = Tint.base(name)?.usingColorSpace(.sRGB) else { return .labelColor }
        return 0.299 * c.redComponent + 0.587 * c.greenComponent + 0.114 * c.blueComponent < 0.6 ? .white : .black
    }

    static let coversBar: CGFloat = 0.6

    private static func base(_ name: String) -> NSColor? {
        if name.hasPrefix("#") {
            guard name.count == 7, let v = UInt32(name.dropFirst(), radix: 16) else { return nil }
            return NSColor(srgbRed: CGFloat(v >> 16 & 0xff) / 255, green: CGFloat(v >> 8 & 0xff) / 255,
                           blue: CGFloat(v & 0xff) / 255, alpha: 1)
        }
        switch name {
        case "red": return .systemRed
        case "orange": return .systemOrange
        case "yellow": return .systemYellow
        case "green": return .systemGreen
        case "mint": return .systemMint
        case "teal": return .systemTeal
        case "cyan": return .systemCyan
        case "blue": return .systemBlue
        case "indigo": return .systemIndigo
        case "purple": return .systemPurple
        case "pink": return .systemPink
        case "brown": return .systemBrown
        case "gray": return .systemGray
        default: return nil
        }
    }

    var diameter: CGFloat {
        switch size {
        case .small: return 4
        case .medium: return 5
        case .large: return 6
        }
    }

    /// A tinted image is color, not a template, so a symbol's own strokes are
    /// drawn in the label color to keep following the bar's appearance. glyph
    /// and accent recolor a symbol's layers; an image with none is left plain.
    func apply(to plain: NSImage, badge: String = "") -> NSImage {
        switch style {
        case .glyph:
            return Tint.untemplated(plain.withSymbolConfiguration(.init(hierarchicalColor: color))) ?? plain
        case .accent:
            return Tint.untemplated(plain.withSymbolConfiguration(.init(paletteColors: [.labelColor, color]))) ?? plain
        case .dot:
            return dot(plain.withSymbolConfiguration(.init(hierarchicalColor: .labelColor)) ?? plain)
        case .chip:
            return chip(plain.withSymbolConfiguration(.init(hierarchicalColor: ink)) ?? plain,
                        badge: wrap == .all ? badge : "")
        }
    }

    /// While the menu is open a chip's patch is clear: macOS puts its own pill
    /// behind the item then. It keeps its size, or the bar redraws the icon
    /// larger without the padding around it.
    func shown(menuOpen: Bool) -> Tint {
        guard menuOpen, style == .chip else { return self }
        var clear = self
        clear.alpha = 0
        return clear
    }

    static func untemplated(_ image: NSImage?) -> NSImage? {
        image?.isTemplate = false
        return image
    }

    /// The icon with a dot on one corner, and a gap cut around the dot so it
    /// reads apart from whatever stroke it lands on.
    func dot(_ icon: NSImage) -> NSImage {
        let size = icon.size, d = diameter, color = color
        let x = corner == .bottomLeft || corner == .topLeft ? 0 : size.width - d
        let y = corner == .bottomLeft || corner == .bottomRight ? 0 : size.height - d
        let spot = NSRect(x: x, y: y, width: d, height: d)
        return Tint.untemplated(NSImage(size: size, flipped: false) { rect in
            icon.draw(in: rect)
            NSGraphicsContext.current?.compositingOperation = .clear
            NSBezierPath(ovalIn: spot.insetBy(dx: -1.5, dy: -1.5)).fill()
            NSGraphicsContext.current?.compositingOperation = .sourceOver
            color.setFill()
            NSBezierPath(ovalIn: spot).fill()
            return true
        })!
    }

    /// The icon on a rounded patch of the color, and the badge beside it on the
    /// same patch when there is one.
    func chip(_ icon: NSImage, badge: String = "") -> NSImage {
        let pad = NSSize(width: 4, height: 2), gap: CGFloat = 3, color = color
        let font = NSFont.menuBarFont(ofSize: 0)
        let label = NSAttributedString(string: badge, attributes: [.font: font, .foregroundColor: ink])
        let text = badge.isEmpty ? .zero : label.size()
        let width = icon.size.width + 2 * pad.width + (badge.isEmpty ? 0 : gap + ceil(text.width))
        let size = NSSize(width: width, height: icon.size.height + 2 * pad.height)
        return Tint.untemplated(NSImage(size: size, flipped: false) { rect in
            color.setFill()
            NSBezierPath(roundedRect: rect, xRadius: 4, yRadius: 4).fill()
            icon.draw(in: NSRect(origin: NSPoint(x: pad.width, y: pad.height), size: icon.size))
            if !badge.isEmpty {
                label.draw(at: NSPoint(x: pad.width + icon.size.width + gap, y: (rect.height - text.height) / 2))
            }
            return true
        })!
    }
}

// MARK: - Prefs

/// The user's own settings, from the app's defaults domain:
/// `defaults write <app id> tint '#5e2ca5'`. Read on every draw, so a change
/// shows at the next poll.
enum Prefs {
    /// The app tint's color, unless the user has set one macOS can draw.
    static func tint(or fallback: String) -> String {
        guard let name = UserDefaults.standard.string(forKey: "tint"), Tint.draws(name) else { return fallback }
        return name
    }
}

// MARK: - Status button

enum StatusButton {
    /// Draws an icon, tinted, with its badge, on the status item's button.
    static func paint(_ image: NSImage?, tint: Tint?, badge: String, dim: Bool, menuOpen: Bool,
                      on button: NSStatusBarButton) {
        let tint = tint?.shown(menuOpen: menuOpen)
        let drawn = image.map { tint?.apply(to: $0, badge: badge) ?? $0 }
        button.image = drawn
        button.alphaValue = MenuIcon.alpha(of: drawn, on: button)
        button.appearsDisabled = dim
        button.title = badge.isEmpty || tint?.wrapsBadge == true ? "" : " " + badge
    }

    /// Calls back as the menu opens and closes, and when another app becomes
    /// active: an image's inactive-bar fade is worked out at draw time, so it
    /// has to be redrawn when the thing it is worked out from moves. The menu
    /// is asked for each time, so one attached later is still followed.
    static func follow(_ menu: @escaping () -> NSMenu?, _ redraw: @escaping (_ menuOpen: Bool) -> Void) {
        var open = false
        for (name, isOpen) in [(NSMenu.didBeginTrackingNotification, true), (NSMenu.didEndTrackingNotification, false)] {
            NotificationCenter.default.addObserver(forName: name, object: nil, queue: nil) { note in
                guard let tracked = note.object as? NSMenu, tracked === menu() else { return }
                open = isOpen
                redraw(open)
            }
        }
        NSWorkspace.shared.notificationCenter.addObserver(
            forName: NSWorkspace.didActivateApplicationNotification, object: nil, queue: .main
        ) { _ in redraw(open) }
    }
}

// MARK: - MenuGlass

/// Tints the dropdown. AppKit has no API for a menu's color, but on macOS 26
/// and later a menu's window is drawn on an NSGlassEffectView, whose tintColor
/// is public. Finding that window goes by its private class name, so a macOS
/// that renames it leaves the menu untinted rather than broken.
enum MenuGlass {
    /// Runs before each menu window first draws, submenus included, so the
    /// tint never arrives a frame late.
    static func follow(_ tint: @escaping () -> Tint?) {
        #if compiler(>=6.2) // the first toolchain with the macOS 26 SDK, where NSGlassEffectView is declared
        guard #available(macOS 26, *) else { return }
        NotificationCenter.default.addObserver(forName: NSWindow.didUpdateNotification, object: nil, queue: nil) { note in
            guard let window = note.object as? NSWindow, String(describing: type(of: window)) == "NSPopupMenuWindow",
                  let glass = glass(in: window.contentView?.superview ?? window.contentView) else { return }
            let t = tint()
            let color = t?.menu == true ? t?.color : nil
            if glass.tintColor != color { glass.tintColor = color }
        }
        #endif
    }

    #if compiler(>=6.2)
    @available(macOS 26, *)
    private static func glass(in view: NSView?) -> NSGlassEffectView? {
        guard let view else { return nil }
        if let glass = view as? NSGlassEffectView { return glass }
        return view.subviews.lazy.compactMap { $0 as? NSGlassEffectView }.first
    }
    #endif
}
