// Generated by perch. Regenerating overwrites this file.
//
// The fixed half of a preview: it reads the outcomes a docs page states, and
// prints what Render.swift decides from them. Only the docs site builds this
// file; the app never carries it.

import Foundation

/// What one poll of one watch returned, as a docs page writes it.
struct Sample: Decodable {
    var code: Int?
    var out: String?
    var err: String?
    var status: Int?
    var exists: Bool?
}

struct SampleState: Decodable {
    var name: String
    var watches: [String: Sample]
}

extension RunOutcome {
    init(sample: Sample) {
        let code = sample.code ?? 0
        self.init(ok: code == 0, code: code, out: sample.out ?? "", err: sample.err ?? "")
    }
}

extension HTTPOutcome {
    init(sample: Sample) {
        let status = sample.status ?? 200
        self.init(ok: (200..<300).contains(status), status: status, out: sample.out ?? "")
    }
}

func readStates() -> [SampleState] {
    let data = FileHandle.standardInput.readDataToEndOfFile()
    do {
        return try JSONDecoder().decode([SampleState].self, from: data)
    } catch {
        FileHandle.standardError.write(Data("preview: unreadable states: \(error)\n".utf8))
        exit(1)
    }
}

func frame(_ state: String, _ face: Face, _ menu: [MenuNode]) -> [String: Any] {
    ["state": state, "face": encoded(face), "menu": menu.map { encoded($0) }]
}

private func encoded(_ icon: MenuIcon) -> [String: Any] {
    switch icon {
    case .symbol(let name): return ["symbol": name]
    case .asset(let name): return ["asset": name]
    }
}

private func encoded(_ face: Face) -> [String: Any] {
    ["icon": encoded(face.icon), "dim": face.dim, "badge": face.badge]
}

private func encoded(_ action: MenuAction) -> [String: Any] {
    switch action {
    case .run(let argv): return ["run": argv]
    case .open(let target): return ["open": target]
    case .post(let url, let body): return ["post": ["url": url, "body": body]]
    case .quit: return ["quit": true]
    }
}

private func encoded(_ node: MenuNode) -> [String: Any] {
    switch node {
    case .separator:
        return ["separator": true]
    case .item(let title, nil):
        return ["title": title]
    case .item(let title, let action?):
        return ["title": title, "action": encoded(action)]
    case .submenu(let title, let items):
        return ["title": title, "items": items.map { encoded($0) }]
    }
}

func emit(_ frames: [Any]) {
    guard let data = try? JSONSerialization.data(withJSONObject: frames, options: [.sortedKeys]) else {
        FileHandle.standardError.write(Data("preview: frames are not JSON\n".utf8))
        exit(1)
    }
    FileHandle.standardOutput.write(data)
}
