// Generated by perch. Regenerating overwrites this file.
//
// The fixed half of the generated app: a JSON value, the three watch pollers,
// and the action verbs. Nothing here depends on menubar.yaml.

import AppKit
import Foundation

// MARK: - MenuIcon

/// What the status item shows. A symbol is drawn as a template, so macOS tints
/// it for the menu bar's own appearance and for whether the bar is selected. An
/// asset is artwork the consuming repo drew, which macOS will not tint and
/// which therefore has to carry its own color.
enum MenuIcon {
    case symbol(String)
    case asset(String)

    func image() -> NSImage? {
        switch self {
        case .symbol(let name):
            let image = NSImage(systemSymbolName: name, accessibilityDescription: nil)
            image?.isTemplate = true
            return image
        case .asset(let name):
            guard let image = MenuIcon.load(name), image.size.height > 0 else { return nil }
            // The menu bar's own height, with the artwork's aspect kept: an
            // asset is shipped at 2x and would otherwise draw at twice the bar.
            let height: CGFloat = 18
            image.size = NSSize(width: height * (image.size.width / image.size.height), height: height)
            return image
        }
    }

    /// `<name>~dark.png` where the bundle carries one. A template gets its two
    /// appearances from macOS; artwork that keeps its own color does not, so an
    /// asset whose outline must read against both menu bars ships both.
    private static func load(_ name: String) -> NSImage? {
        let dark = NSApp.effectiveAppearance.bestMatch(from: [.aqua, .darkAqua]) == .darkAqua
        if dark, let path = Bundle.main.path(forResource: name + "~dark", ofType: "png"),
           let image = NSImage(contentsOfFile: path) {
            return image
        }
        guard let path = Bundle.main.path(forResource: name, ofType: "png") else { return nil }
        return NSImage(contentsOfFile: path)
    }
}

// MARK: - JSONValue

/// The value an undeclared watch binds. A watch with a `shape:` decodes into a
/// generated struct instead and never touches this.
enum JSONValue: Equatable {
    case null
    case bool(Bool)
    case int(Int)
    case double(Double)
    case string(String)
    case array([JSONValue])
    case object([String: JSONValue])
}

extension JSONValue: Decodable {
    init(from decoder: Decoder) throws {
        if let c = try? decoder.singleValueContainer() {
            if c.decodeNil() {
                self = .null
                return
            }
            if let v = try? c.decode(Bool.self) {
                self = .bool(v)
                return
            }
            if let v = try? c.decode(Int.self) {
                self = .int(v)
                return
            }
            if let v = try? c.decode(Double.self) {
                self = .double(v)
                return
            }
            if let v = try? c.decode(String.self) {
                self = .string(v)
                return
            }
            if let v = try? c.decode([JSONValue].self) {
                self = .array(v)
                return
            }
            if let v = try? c.decode([String: JSONValue].self) {
                self = .object(v)
                return
            }
        }
        self = .null
    }

    static func parse(_ text: String) -> JSONValue {
        guard let data = text.data(using: .utf8) else { return .null }
        return (try? JSONDecoder().decode(JSONValue.self, from: data)) ?? .null
    }
}

extension JSONValue {
    init(_ v: Bool) { self = .bool(v) }
    init(_ v: Int) { self = .int(v) }
    init(_ v: Double) { self = .double(v) }
    init(_ v: String) { self = .string(v) }

    subscript(key: String) -> JSONValue {
        if case .object(let o) = self { return o[key] ?? .null }
        return .null
    }

    subscript(index: Int) -> JSONValue {
        if case .array(let a) = self, a.indices.contains(index) { return a[index] }
        return .null
    }

    var exists: Bool { self != .null }

    var asBool: Bool {
        switch self {
        case .bool(let b): return b
        case .int(let i): return i != 0
        case .double(let d): return d != 0
        case .string(let s): return !s.isEmpty
        case .array(let a): return !a.isEmpty
        case .object(let o): return !o.isEmpty
        case .null: return false
        }
    }

    var asInt: Int {
        switch self {
        case .int(let i): return i
        // Int(Double) traps outside Int's range, and the double came from
        // whatever the watch printed.
        case .double(let d): return Int(exactly: d.rounded()) ?? 0
        case .bool(let b): return b ? 1 : 0
        case .string(let s): return Int(s) ?? 0
        default: return 0
        }
    }

    var asDouble: Double {
        switch self {
        case .double(let d): return d
        case .int(let i): return Double(i)
        case .bool(let b): return b ? 1 : 0
        case .string(let s): return Double(s) ?? 0
        default: return 0
        }
    }

    var asString: String {
        switch self {
        case .string(let s): return s
        case .int(let i): return String(i)
        case .double(let d):
            if d == d.rounded(), let i = Int(exactly: d) { return String(i) }
            return String(d)
        case .bool(let b): return String(b)
        case .null: return ""
        case .array, .object: return ""
        }
    }

    var asArray: [JSONValue] {
        if case .array(let a) = self { return a }
        return []
    }

    var size: Int {
        switch self {
        case .array(let a): return a.count
        case .object(let o): return o.count
        case .string(let s): return s.count
        default: return 0
        }
    }

    func contains(_ needle: JSONValue) -> Bool { asArray.contains(needle) }
}

// MARK: - Boxes

/// A value one thread fills in and another reads. Used where a completion
/// handler outlives the call that started it.
private final class Box<T> {
    private var value: T
    private let lock = NSLock()

    init(_ initial: T) { value = initial }

    func mutate(_ body: (inout T) -> Void) {
        lock.lock()
        defer { lock.unlock() }
        body(&value)
    }

    var current: T {
        lock.lock()
        defer { lock.unlock() }
        return value
    }
}

// MARK: - Watches

struct RunOutcome {
    var ok = false
    var code = -1
    var out = ""
    var err = ""
}

struct HTTPOutcome {
    var ok = false
    var status = 0
    var out = ""
}

enum Watcher {
    /// Runs argv directly — never a shell. /usr/bin/env performs the PATH
    /// lookup, which a LaunchAgent's minimal environment would otherwise miss.
    static func run(_ argv: [String]) -> RunOutcome {
        guard !argv.isEmpty else { return RunOutcome() }
        let task = Process()
        task.executableURL = URL(fileURLWithPath: "/usr/bin/env")
        task.arguments = argv
        let outPipe = Pipe()
        let errPipe = Pipe()
        task.standardOutput = outPipe
        task.standardError = errPipe
        do {
            try task.run()
        } catch {
            return RunOutcome(ok: false, code: -1, out: "", err: "\(error)")
        }
        // Both pipes drain at once. Reading one to EOF and then the other
        // deadlocks a child that fills the second pipe's buffer meanwhile.
        let stderrBox = Box(Data())
        let draining = DispatchQueue(label: "perch.run.stderr")
        draining.async {
            stderrBox.mutate { $0 = errPipe.fileHandleForReading.readDataToEndOfFile() }
        }
        let outData = outPipe.fileHandleForReading.readDataToEndOfFile()
        draining.sync {}
        let errData = stderrBox.current
        task.waitUntilExit()
        let code = Int(task.terminationStatus)
        return RunOutcome(
            ok: code == 0,
            code: code,
            out: String(data: outData, encoding: .utf8) ?? "",
            err: String(data: errData, encoding: .utf8) ?? ""
        )
    }

    static func http(_ urlString: String) -> HTTPOutcome {
        guard let url = URL(string: urlString) else { return HTTPOutcome() }
        // Boxed because the wait below can time out while the request is still
        // in flight, leaving the handler to write after this call has returned.
        let box = Box(HTTPOutcome())
        let done = DispatchSemaphore(value: 0)
        var request = URLRequest(url: url)
        request.timeoutInterval = 5
        URLSession.shared.dataTask(with: request) { data, response, _ in
            box.mutate { outcome in
                if let http = response as? HTTPURLResponse {
                    outcome.status = http.statusCode
                    outcome.ok = (200..<300).contains(http.statusCode)
                }
                if let data { outcome.out = String(data: data, encoding: .utf8) ?? "" }
            }
            done.signal()
        }.resume()
        _ = done.wait(timeout: .now() + 10)
        return box.current
    }

    static func exists(_ path: String) -> Bool {
        FileManager.default.fileExists(atPath: (path as NSString).expandingTildeInPath)
    }
}

// MARK: - Actions

enum Act {
    /// Every action re-polls on completion, so acting on the menu visibly
    /// changes it. A non-zero exit raises an alert naming the command.
    static func run(_ argv: [String], then repoll: @escaping () -> Void) {
        DispatchQueue.global(qos: .userInitiated).async {
            let outcome = Watcher.run(argv)
            DispatchQueue.main.async {
                if !outcome.ok { alert(argv.joined(separator: " "), outcome.err) }
                repoll()
            }
        }
    }

    static func open(_ target: String) {
        if let url = URL(string: target), url.scheme != nil {
            NSWorkspace.shared.open(url)
        } else {
            NSWorkspace.shared.open(URL(fileURLWithPath: (target as NSString).expandingTildeInPath))
        }
    }

    static func post(_ urlString: String, body: String, then repoll: @escaping () -> Void) {
        guard let url = URL(string: urlString) else {
            alert("POST \(urlString)", "Not a URL.")
            return
        }
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.httpBody = body.data(using: .utf8)
        URLSession.shared.dataTask(with: request) { _, response, error in
            DispatchQueue.main.async {
                let status = (response as? HTTPURLResponse)?.statusCode ?? 0
                if error != nil || !(200..<300).contains(status) {
                    alert("POST \(urlString)", error?.localizedDescription ?? "HTTP \(status)")
                }
                repoll()
            }
        }.resume()
    }

    static func alert(_ command: String, _ detail: String) {
        let a = NSAlert()
        a.messageText = "\(command) failed"
        a.informativeText = detail.isEmpty ? "No output." : detail
        a.alertStyle = .warning
        a.runModal()
    }
}

// MARK: - Menu

/// An NSMenuItem that carries its own closure, so the generated menu builder
/// does not need a selector per action.
final class ActionItem: NSMenuItem {
    private let handler: () -> Void

    init(title: String, handler: @escaping () -> Void) {
        self.handler = handler
        super.init(title: title, action: nil, keyEquivalent: "")
        self.target = self
        self.action = #selector(fire)
    }

    @available(*, unavailable)
    required init(coder: NSCoder) { fatalError("not supported") }

    @objc private func fire() { handler() }
}
