// Generated by perch from menubar.yaml. Regenerating overwrites this file.

import AppKit
import Foundation

struct FleetResult {
    var ok = false
    var code = -1
    var out = ""
    var err = ""
    var data: FleetData = FleetData()
}

struct Results {
    var fleet = FleetResult()
}

final class Controller: NSObject, NSApplicationDelegate, NSMenuDelegate {
    private let statusItem = NSStatusBar.system.statusItem(withLength: NSStatusItem.variableLength)
    private var results = Results()
    private var timer: Timer?

    override init() {
        super.init()
        let menu = NSMenu()
        menu.delegate = self
        statusItem.menu = menu
        refresh()
        poll()
        timer = Timer.scheduledTimer(withTimeInterval: 5.0, repeats: true) { [weak self] _ in
            self?.poll()
        }
    }

    func poll() {
        let group = DispatchGroup()
        let sync = DispatchQueue(label: "dev.onto.menubar.results")
        var next = Results()

        group.enter()
        DispatchQueue.global(qos: .utility).async {
            var r = FleetResult()
            let o = Watcher.run(["onto", "top", "--once", "--json"])
            r.ok = o.ok
            r.code = o.code
            r.out = o.out
            r.err = o.err
            r.data = (try? JSONDecoder().decode(FleetData.self, from: Data(o.out.utf8))) ?? FleetData()
            sync.async {
                next.fleet = r
                group.leave()
            }
        }

        group.notify(queue: .main) { [weak self] in
            guard let self else { return }
            self.results = sync.sync { next }
            self.refresh()
            if let menu = self.statusItem.menu, menu.numberOfItems > 0 { self.menuNeedsUpdate(menu) }
        }
    }

    func refresh() {
        guard let button = statusItem.button else { return }
        var icon = "rectangle.3.group"
        var dim = false
        var badge = ""
        if !(self.results.fleet.ok) {
            icon = "exclamationmark.triangle"
        } else if (self.results.fleet.data.jobs.count == 0) {
            dim = true
        } else {
            badge = String(self.results.fleet.data.jobs.count)
        }
        let image = NSImage(systemSymbolName: icon, accessibilityDescription: nil)
        image?.isTemplate = true
        button.image = image
        button.appearsDisabled = dim
        button.title = badge.isEmpty ? "" : " " + badge
    }

    func menuNeedsUpdate(_ menu: NSMenu) {
        menu.removeAllItems()
        menu.addItem(NSMenuItem(title: "\(String(self.results.fleet.data.nodes.count)) nodes · \(String(self.results.fleet.data.jobs.count)) running", action: nil, keyEquivalent: ""))
        menu.addItem(NSMenuItem.separator())
        for it1 in self.results.fleet.data.jobs {
            let item2 = NSMenuItem(title: "\(it1.node) — \(it1.cmd)", action: nil, keyEquivalent: "")
            let sub3 = NSMenu()
            sub3.addItem(ActionItem(title: "Logs") { [weak self] in
                Act.run(["onto", "logs", "\(it1.id)"]) { self?.poll() }
            })
            sub3.addItem(ActionItem(title: "Prune") { [weak self] in
                Act.run(["onto", "prune", "\(it1.id)"]) { self?.poll() }
            })
            sub3.addItem(ActionItem(title: "Kill") { [weak self] in
                Act.run(["onto", "kill", "\(it1.id)"]) { self?.poll() }
            })
            item2.submenu = sub3
            menu.addItem(item2)
        }
        menu.addItem(NSMenuItem.separator())
        menu.addItem(ActionItem(title: "Quit") {
            NSApp.terminate(nil)
        })
    }
}

let app = NSApplication.shared
app.setActivationPolicy(.accessory)
let controller = Controller()
app.delegate = controller
app.run()
