// Generated by perch from menubar.yaml. Regenerating overwrites this file.

import Foundation

struct FleetResult {
    var ok = false
    var code = -1
    var out = ""
    var err = ""
    var data: FleetData = FleetData()
}

struct Results {
    var fleet = FleetResult()
}

extension FleetResult {
    init(_ o: RunOutcome) {
        self.init()
        ok = o.ok
        code = o.code
        out = o.out
        err = o.err
        data = (try? JSONDecoder().decode(FleetData.self, from: Data(o.out.utf8))) ?? FleetData()
    }
}

func renderFace(_ results: Results) -> Face {
    var face = Face(icon: MenuIcon.symbol("rectangle.3.group"))
    if !(results.fleet.ok) {
        face.icon = MenuIcon.symbol("exclamationmark.triangle")
    } else if (results.fleet.data.jobs.count == 0) {
        face.dim = true
    } else {
        face.badge = String(results.fleet.data.jobs.count)
    }
    return face
}

func renderMenu(_ results: Results) -> [MenuNode] {
    var menu: [MenuNode] = []
    menu.append(.item("\(String(results.fleet.data.nodes.count)) nodes · \(String(results.fleet.data.jobs.count)) running", nil))
    menu.append(.separator)
    for it1 in results.fleet.data.jobs {
        var sub2: [MenuNode] = []
        sub2.append(.item("Logs", .run(["onto", "logs", "\(it1.id)"])))
        sub2.append(.item("Prune", .run(["onto", "prune", "\(it1.id)"])))
        sub2.append(.item("Kill", .run(["onto", "kill", "\(it1.id)"])))
        menu.append(.submenu("\(it1.node) — \(it1.cmd)", sub2))
    }
    menu.append(.separator)
    menu.append(.item("Quit", .quit))
    return tidy(menu)
}
