// Generated by perch from menubar.yaml. Regenerating overwrites this file.

import Foundation

struct FleetData: Decodable {
    var nodes: [FleetDataNodes] = []
    var jobs: [FleetDataJobs] = []

    init() {}

    private enum CodingKeys: String, CodingKey {
        case nodes
        case jobs
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.nodes = (try? c.decode([FleetDataNodes].self, forKey: .nodes)) ?? []
        self.jobs = (try? c.decode([FleetDataJobs].self, forKey: .jobs)) ?? []
    }
}

struct FleetDataNodes: Decodable {
    var name: String = ""
    var up: Bool = false

    init() {}

    private enum CodingKeys: String, CodingKey {
        case name
        case up
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.name = (try? c.decode(String.self, forKey: .name)) ?? ""
        self.up = (try? c.decode(Bool.self, forKey: .up)) ?? false
    }
}

struct FleetDataJobs: Decodable {
    var id: String = ""
    var node: String = ""
    var cmd: String = ""

    init() {}

    private enum CodingKeys: String, CodingKey {
        case id
        case node
        case cmd
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.id = (try? c.decode(String.self, forKey: .id)) ?? ""
        self.node = (try? c.decode(String.self, forKey: .node)) ?? ""
        self.cmd = (try? c.decode(String.self, forKey: .cmd)) ?? ""
    }
}

