// Generated by perch from menubar.yaml. Regenerating overwrites this file.

import Foundation

struct WorkerResult {
    var installed = false
    var loaded = false
    var running = false
    var pid = 0
    var label = ""
    var plist = ""
    var domain = ""
    var target = ""
}

struct Results {
    var worker = WorkerResult()
}

extension WorkerResult {
    init(_ o: LaunchAgentOutcome) {
        self.init()
        installed = o.installed
        loaded = o.loaded
        running = o.running
        pid = o.pid
        label = o.label
        plist = o.plist
        domain = Launchd.domain
        target = Launchd.target(o.label)
    }
}

extension Results {
    var state_uninstalled: Bool { (!(worker.installed)) }
    var state_stopped: Bool { !state_uninstalled && (!(worker.loaded)) }
    var state_idle: Bool { !state_uninstalled && !state_stopped && (!(worker.running)) }
    var state_running: Bool { !state_uninstalled && !state_stopped && !state_idle }
}

func renderFace(_ results: Results) -> Face {
    var face = Face(icon: MenuIcon.symbol("gearshape"))
    if results.state_uninstalled {
        face.icon = MenuIcon.symbol("exclamationmark.triangle")
    } else if (results.state_stopped || results.state_idle) {
        face.dim = true
    }
    return face
}

func renderMenu(_ results: Results) -> [MenuNode] {
    var menu: [MenuNode] = []
    if results.state_running {
        menu.append(.item("Running · pid \(String(results.worker.pid))", nil))
    }
    if results.state_idle {
        menu.append(.item("Loaded, not running", nil))
    }
    if results.state_stopped {
        menu.append(.item("Not loaded", nil))
    }
    if results.state_uninstalled {
        menu.append(.item("Not installed", nil))
    }
    menu.append(.separator)
    if results.state_stopped {
        menu.append(.item("Start", .agent(label: "dev.example.worker", plist: "~/Library/LaunchAgents/dev.example.worker.plist", verb: .start)))
    }
    if (results.state_running || results.state_idle) {
        menu.append(.item("Stop", .agent(label: "dev.example.worker", plist: "~/Library/LaunchAgents/dev.example.worker.plist", verb: .stop)))
    }
    if !(results.state_uninstalled) {
        menu.append(.item("Restart", .agent(label: "dev.example.worker", plist: "~/Library/LaunchAgents/dev.example.worker.plist", verb: .restart)))
    }
    if results.worker.loaded {
        menu.append(.item("Blame", .run(["launchctl", "blame", "\(results.worker.target)"])))
    }
    menu.append(.item("Quit", .quit))
    return menu
}
