// Generated by perch from menubar.yaml. Regenerating overwrites this file.

import AppKit
import Foundation

final class Controller: NSObject, NSApplicationDelegate, NSMenuDelegate {
    private let statusItem = NSStatusBar.system.statusItem(withLength: NSStatusItem.variableLength)
    fileprivate var results = Results()
    private var timer: Timer?

    override init() {
        super.init()
        let menu = NSMenu()
        menu.delegate = self
        statusItem.menu = menu
        NSWorkspace.shared.notificationCenter.addObserver(
            forName: NSWorkspace.didActivateApplicationNotification, object: nil, queue: .main
            ) { [weak self] _ in self?.refresh() }
        refresh()
        poll()
        timer = Timer.scheduledTimer(withTimeInterval: 5.0, repeats: true) { [weak self] _ in
            self?.poll()
        }
    }

    fileprivate func poll() {
        let group = DispatchGroup()
        let sync = DispatchQueue(label: "dev.example.wall.menubar.results")
        var next = Results()

        group.enter()
        DispatchQueue.global(qos: .utility).async {
            let r = HealthResult(Watcher.http("http://127.0.0.1:8787/api/health"))
            sync.async {
                next.health = r
                group.leave()
            }
        }

        group.enter()
        DispatchQueue.global(qos: .utility).async {
            let r = DaemonAgentResult(Watcher.launchAgent(label: "dev.example.wall.daemon", plist: "~/Library/LaunchAgents/dev.example.wall.daemon.plist"))
            sync.async {
                next.daemon.agent = r
                group.leave()
            }
        }

        group.enter()
        DispatchQueue.global(qos: .utility).async {
            let r = ClientAgentResult(Watcher.launchAgent(label: "dev.example.wall.client", plist: "~/Library/LaunchAgents/dev.example.wall.client.plist"))
            sync.async {
                next.client.agent = r
                group.leave()
            }
        }

        group.notify(queue: .main) { [weak self] in
            guard let self else { return }
            self.results = sync.sync { next }
            self.refresh()
            if let menu = self.statusItem.menu, menu.numberOfItems > 0 { self.menuNeedsUpdate(menu) }
        }
    }

    func refresh() {
        guard let button = statusItem.button else { return }
        Draw.face(renderFace(results), on: button)
    }

    func menuNeedsUpdate(_ menu: NSMenu) {
        Draw.menu(renderMenu(results), into: menu) { [weak self] in self?.poll() }
    }
}

let app = NSApplication.shared
app.setActivationPolicy(.accessory)
let controller = Controller()
app.delegate = controller
app.run()
