// Generated by perch from menubar.yaml. Regenerating overwrites this file.

import Foundation

struct HealthResult {
    var ok = false
    var status = 0
    var out = ""
}

struct DaemonAgentResult {
    var installed = false
    var loaded = false
    var running = false
    var pid = 0
    var label = ""
    var plist = ""
    var domain = ""
    var target = ""
}

struct ClientAgentResult {
    var installed = false
    var loaded = false
    var running = false
    var pid = 0
    var label = ""
    var plist = ""
    var domain = ""
    var target = ""
}

struct DaemonUse {
    var agent = DaemonAgentResult()
}

struct ClientUse {
    var agent = ClientAgentResult()
}

struct Results {
    var health = HealthResult()
    var daemon = DaemonUse()
    var client = ClientUse()
}

extension HealthResult {
    init(_ o: HTTPOutcome) {
        self.init()
        ok = o.ok
        status = o.status
        out = o.out
    }
}

extension DaemonAgentResult {
    init(_ o: LaunchAgentOutcome) {
        self.init()
        installed = o.installed
        loaded = o.loaded
        running = o.running
        pid = o.pid
        label = o.label
        plist = o.plist
        domain = Launchd.domain
        target = Launchd.target(o.label)
    }
}

extension ClientAgentResult {
    init(_ o: LaunchAgentOutcome) {
        self.init()
        installed = o.installed
        loaded = o.loaded
        running = o.running
        pid = o.pid
        label = o.label
        plist = o.plist
        domain = Launchd.domain
        target = Launchd.target(o.label)
    }
}

extension DaemonUse {
    var uninstalled: Bool { (!(self.agent.installed)) }
    var stopped: Bool { !self.uninstalled && (!(self.agent.loaded)) }
    var idle: Bool { !self.uninstalled && !self.stopped && (!(self.agent.running)) }
    var running: Bool { !self.uninstalled && !self.stopped && !self.idle }
}

extension ClientUse {
    var uninstalled: Bool { (!(self.agent.installed)) }
    var stopped: Bool { !self.uninstalled && (!(self.agent.loaded)) }
    var idle: Bool { !self.uninstalled && !self.stopped && (!(self.agent.running)) }
    var running: Bool { !self.uninstalled && !self.stopped && !self.idle }
}

extension Results {
    var state_down: Bool { (!(self.daemon.running)) }
    var state_wedged: Bool { !self.state_down && (!(self.health.ok)) }
    var state_up: Bool { !self.state_down && !self.state_wedged }
}

func renderFace(_ results: Results) -> Face {
    var face = Face(icon: MenuIcon.symbol("rectangle.stack"))
    if results.daemon.uninstalled {
        face.icon = MenuIcon.symbol("exclamationmark.triangle")
    } else if results.client.uninstalled {
        face.icon = MenuIcon.symbol("exclamationmark.triangle")
    } else if results.state_down {
        face.dim = true
    }
    return face
}

func renderMenu(_ results: Results) -> [MenuNode] {
    var menu: [MenuNode] = []
    if results.daemon.uninstalled {
        menu.append(.item("Service: not installed", nil))
    }
    if results.daemon.stopped {
        menu.append(.item("Service: not loaded", nil))
    }
    if results.daemon.idle {
        menu.append(.item("Service: loaded, not running", nil))
    }
    if results.daemon.running {
        menu.append(.item("Service: running · pid \(String(results.daemon.agent.pid))", nil))
    }
    if results.client.uninstalled {
        menu.append(.item("Client: not installed", nil))
    }
    if results.client.stopped {
        menu.append(.item("Client: not loaded", nil))
    }
    if results.client.idle {
        menu.append(.item("Client: loaded, not running", nil))
    }
    if results.client.running {
        menu.append(.item("Client: running · pid \(String(results.client.agent.pid))", nil))
    }
    menu.append(.separator)
    if results.state_up {
        menu.append(.item("pid \(String(results.daemon.agent.pid))", nil))
    }
    if (results.daemon.agent.installed && !(results.daemon.agent.loaded)) {
        menu.append(.item("Start Service", .agent(label: "dev.example.wall.daemon", plist: "~/Library/LaunchAgents/dev.example.wall.daemon.plist", verb: .start)))
    }
    if results.daemon.agent.installed {
        menu.append(.item("Restart Service", .agent(label: "dev.example.wall.daemon", plist: "~/Library/LaunchAgents/dev.example.wall.daemon.plist", verb: .restart)))
    }
    if results.daemon.agent.loaded {
        menu.append(.item("Stop Service", .agent(label: "dev.example.wall.daemon", plist: "~/Library/LaunchAgents/dev.example.wall.daemon.plist", verb: .stop)))
    }
    if (results.client.agent.installed && !(results.client.agent.loaded)) {
        menu.append(.item("Start Client", .agent(label: "dev.example.wall.client", plist: "~/Library/LaunchAgents/dev.example.wall.client.plist", verb: .start)))
    }
    if results.client.agent.installed {
        menu.append(.item("Restart Client", .agent(label: "dev.example.wall.client", plist: "~/Library/LaunchAgents/dev.example.wall.client.plist", verb: .restart)))
    }
    if results.client.agent.loaded {
        menu.append(.item("Stop Client", .agent(label: "dev.example.wall.client", plist: "~/Library/LaunchAgents/dev.example.wall.client.plist", verb: .stop)))
    }
    menu.append(.separator)
    menu.append(.item("Quit", .quit))
    return tidy(menu)
}
