// Generated by perch from menubar.yaml. Regenerating overwrites this file.

import AppKit
import Foundation

final class Controller: NSObject, NSApplicationDelegate, NSMenuDelegate {
    private let statusItem = NSStatusBar.system.statusItem(withLength: NSStatusItem.variableLength)
    private var results = Results()
    private var timer: Timer?

    override init() {
        super.init()
        let menu = NSMenu()
        menu.delegate = self
        statusItem.menu = menu
        NSWorkspace.shared.notificationCenter.addObserver(
            forName: NSWorkspace.didActivateApplicationNotification, object: nil, queue: .main
            ) { [weak self] _ in self?.refresh() }
        refresh()
        poll()
        timer = Timer.scheduledTimer(withTimeInterval: 3.0, repeats: true) { [weak self] _ in
            self?.poll()
        }
    }

    func poll() {
        refresh()
    }

    func refresh() {
        guard let button = statusItem.button else { return }
        Draw.face(renderFace(results), on: button)
    }

    func menuNeedsUpdate(_ menu: NSMenu) {
        Draw.menu(renderMenu(results), into: menu) { [weak self] in self?.poll() }
    }
}

let app = NSApplication.shared
app.setActivationPolicy(.accessory)
let controller = Controller()
app.delegate = controller
app.run()
