// Generated by perch from menubar.yaml. Regenerating overwrites this file.

import AppKit
import Foundation

struct Results {
    // no watches declared
}

final class Controller: NSObject, NSApplicationDelegate, NSMenuDelegate {
    private let statusItem = NSStatusBar.system.statusItem(withLength: NSStatusItem.variableLength)
    private var results = Results()
    private var timer: Timer?

    override init() {
        super.init()
        let menu = NSMenu()
        menu.delegate = self
        statusItem.menu = menu
        refresh()
        poll()
        timer = Timer.scheduledTimer(withTimeInterval: 3.0, repeats: true) { [weak self] _ in
            self?.poll()
        }
    }

    func poll() {
        refresh()
    }

    func refresh() {
        guard let button = statusItem.button else { return }
        let icon = "circle"
        let dim = false
        let badge = ""
        let image = NSImage(systemSymbolName: icon, accessibilityDescription: nil)
        image?.isTemplate = true
        button.image = image
        button.appearsDisabled = dim
        button.title = badge.isEmpty ? "" : " " + badge
    }

    func menuNeedsUpdate(_ menu: NSMenu) {
        menu.removeAllItems()
        menu.addItem(ActionItem(title: "Quit") {
            NSApp.terminate(nil)
        })
    }
}

let app = NSApplication.shared
app.setActivationPolicy(.accessory)
let controller = Controller()
app.delegate = controller
app.run()
