// Generated by perch from menubar.yaml. Regenerating overwrites this file.

import Foundation

struct Results {
    // no watches declared
}

func renderFace(_ results: Results) -> Face {
    let face = Face(icon: MenuIcon.symbol("circle"))
    return face
}

func renderMenu(_ results: Results) -> [MenuNode] {
    var menu: [MenuNode] = []
    menu.append(.item("Quit", .quit))
    return menu
}
