// Package schema emits the JSON Schema an editor uses for completion and
// inline errors, via the yaml-language-server header in menubar.yaml.
package schema

import (
	"encoding/json"
	"fmt"
)

// JSON is the schema for menubar.yaml. It mirrors what spec.Parse accepts;
// where the two could drift, spec.Parse is the authority.
func JSON() string { return body }

const body = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "menubar.yaml",
  "description": "A macOS menu bar app, generated by perch.",
  "type": "object",
  "required": ["app"],
  "additionalProperties": false,
  "properties": {
    "app": {
      "type": "object",
      "required": ["name", "id", "icon", "interval"],
      "additionalProperties": false,
      "properties": {
        "name": {"type": "string", "pattern": "^[^./\\\\][^/\\\\]*$", "description": "Bundle and executable name; one path component under ~/Applications."},
        "id": {"type": "string", "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]*$", "description": "Bundle identifier, e.g. dev.example.menubar."},
        "icon": {"description": "An SF Symbol name, or {asset: <name>} for a .png in menubar/Icons.", "oneOf": [{"type": "string"}, {"type": "object", "required": ["asset"], "additionalProperties": false, "properties": {"asset": {"type": "string", "pattern": "^[A-Za-z0-9_-]+$"}}}]},
        "interval": {"type": "string", "pattern": "^([0-9]+(\\.[0-9]+)?(ns|us|\u00b5s|ms|s|m|h))+$", "description": "Poll interval, e.g. 5s or 1m30s."},
        "sign": {"type": "string", "description": "Keychain code signing identity for the .app. Omit to sign ad-hoc."},
        "quit": {
          "type": "array",
          "description": "What quitting asks first. First matching rule wins; the last takes no when:.",
          "items": {
            "type": "object",
            "required": ["confirm"],
            "additionalProperties": false,
            "properties": {
              "when": {"type": "string", "description": "CEL condition; omit on the last rule."},
              "confirm": {"type": "string", "description": "The question."},
              "detail": {"type": "string", "description": "The smaller text under it."},
              "buttons": {
                "type": "array",
                "description": "Offered in order; the first is the default, Cancel is implicit and last.",
                "items": {
                  "type": "object",
                  "required": ["text"],
                  "additionalProperties": false,
                  "properties": {
                    "text": {"type": "string"},
                    "run": {"type": "array", "minItems": 1, "items": {"type": "string"}},
                    "open": {"type": "string"},
                    "post": {"type": "object", "required": ["url"], "additionalProperties": false, "properties": {"url": {"type": "string"}, "body": {}}},
                    "agent": {"type": "string", "pattern": "^([A-Za-z_][A-Za-z0-9_]*\\.){1,2}(start|stop|restart)$"},
                    "swift": {"type": "string", "pattern": "^[A-Za-z_][A-Za-z0-9_]*\\.[A-Za-z_][A-Za-z0-9_]*$"}
                  }
                }
              }
            }
          }
        }
      }
    },
    "watch": {
      "type": "object",
      "description": "Named sources, polled concurrently every interval.",
      "propertyNames": {"pattern": "^[A-Za-z_][A-Za-z0-9_]*$", "not": {"enum": ["it", "self", "init", "Type", "Protocol", "as", "break", "const", "continue", "else", "false", "for", "function", "if", "import", "in", "let", "loop", "namespace", "null", "package", "return", "true", "var", "void", "while"]}},
      "additionalProperties": {
        "type": "object",
        "additionalProperties": false,
        "oneOf": [
          {"required": ["run"]},
          {"required": ["http"]},
          {"required": ["exists"]},
          {"required": ["launchagent"]}
        ],
        "properties": {
          "run": {"type": "array", "minItems": 1, "items": {"type": "string"}, "description": "argv, never a shell."},
          "http": {"type": "string", "description": "URL; .ok is a 2xx."},
          "exists": {"type": "string", "description": "Path; binds .ok only."},
          "launchagent": {"type": "string", "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]*$", "description": "A launchd label, e.g. dev.example.worker. Binds .installed, .loaded, .running, .pid, .label, .plist, .domain, .target."},
          "plist": {"type": "string", "description": "Where the LaunchAgent file is; defaults to ~/Library/LaunchAgents/<label>.plist. Needs launchagent."},
          "json": {"type": "boolean", "description": "Decode the output into .data."},
          "shape": {"$ref": "#/definitions/shape"}
        }
      }
    },
    "state": {
      "type": "array",
      "description": "Named states, first match wins. The last takes no condition and is the fallback, so exactly one state always holds.",
      "items": {
        "type": "object",
        "minProperties": 1,
        "maxProperties": 1,
        "additionalProperties": {"type": ["string", "null"], "description": "CEL condition reaching this state; omit on the last one."},
        "propertyNames": {"pattern": "^[A-Za-z_][A-Za-z0-9_]*$", "not": {"enum": ["it", "self", "init", "Type", "Protocol"]}}
      }
    },
    "use": {
      "type": "object",
      "description": "Named uses of templates. Each takes exactly one template, and its arguments.",
      "propertyNames": {"pattern": "^[A-Za-z_][A-Za-z0-9_]*$", "not": {"enum": ["it", "self", "init", "Type", "Protocol", "as", "break", "const", "continue", "else", "false", "for", "function", "if", "import", "in", "let", "loop", "namespace", "null", "package", "return", "true", "var", "void", "while"]}},
      "additionalProperties": {
        "type": "object",
        "minProperties": 1,
        "maxProperties": 1,
        "additionalProperties": {"type": ["object", "null"], "additionalProperties": {"type": ["string", "number", "boolean"]}}
      }
    },
    "status": {
      "type": "array",
      "description": "First matching rule wins. An outlet item places the uses' status rules.",
      "items": {
        "oneOf": [
          {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "when": {"type": "string", "description": "CEL condition; omit to always match."},
              "icon": {"description": "An SF Symbol name, or {asset: <name>} for a .png in menubar/Icons.", "oneOf": [{"type": "string"}, {"type": "object", "required": ["asset"], "additionalProperties": false, "properties": {"asset": {"type": "string", "pattern": "^[A-Za-z0-9_-]+$"}}}]},
              "dim": {"type": "boolean"},
              "badge": {"type": "string", "description": "CEL expression shown beside the icon."}
            }
          },
          {"$ref": "#/definitions/outletMark"},
          {"$ref": "#/definitions/namedOutlet"}
        ]
      }
    },
    "window": {
      "type": "object",
      "description": "One WebKit window, opened from a menu item.",
      "required": ["url"],
      "additionalProperties": false,
      "properties": {
        "url": {"type": "string", "description": "The page the window loads."},
        "title": {"type": "string", "description": "Window title; defaults to app.name."},
        "size": {"type": "array", "minItems": 2, "maxItems": 2, "items": {"type": "integer", "minimum": 1}, "description": "[width, height] in points; defaults to [1024, 768]."},
        "zoom": {
          "type": "object",
          "description": "Page zoom bounds. Omit for no zoom controls.",
          "required": ["min", "max", "step"],
          "additionalProperties": false,
          "properties": {
            "min": {"type": "number", "exclusiveMinimum": 0},
            "max": {"type": "number", "exclusiveMinimum": 0},
            "step": {"type": "number", "exclusiveMinimum": 0}
          }
        }
      }
    },
    "menu": {"$ref": "#/definitions/menu"}
  },
  "definitions": {
    "shape": {
      "description": "What a command prints: string, int, double, bool, any, objects, and [T].",
      "oneOf": [
        {"type": "string", "enum": ["string", "int", "double", "bool", "any"]},
        {"type": "array", "minItems": 1, "maxItems": 1, "items": {"$ref": "#/definitions/shape"}},
        {"type": "object", "propertyNames": {"pattern": "^[A-Za-z_][A-Za-z0-9_]*$", "not": {"enum": ["init", "Type", "Protocol"]}}, "additionalProperties": {"$ref": "#/definitions/shape"}}
      ]
    },
    "menu": {
      "type": "array",
      "items": {
        "oneOf": [
          {"type": "string", "enum": ["separator", "outlet"]},
          {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "text": {"type": "string", "description": "Label; {{ }} holes are CEL."},
              "when": {"type": "string", "description": "CEL condition deciding whether the item appears."},
              "each": {"type": "string", "description": "CEL list expression; the element binds to it."},
              "menu": {"$ref": "#/definitions/menu"},
              "run": {"type": "array", "minItems": 1, "items": {"type": "string"}, "description": "argv, never a shell."},
              "open": {"type": "string", "description": "URL or path."},
              "post": {
                "type": "object",
                "required": ["url"],
                "additionalProperties": false,
                "properties": {"url": {"type": "string"}, "body": {}}
              },
              "quit": {"type": "boolean"},
              "agent": {"type": "string", "pattern": "^([A-Za-z_][A-Za-z0-9_]*\\.){1,2}(start|stop|restart)$", "description": "<watch>, <use>.<watch> or self.<watch>, then .start, .stop or .restart."},
              "swift": {"type": "string", "pattern": "^[A-Za-z_][A-Za-z0-9_]*\\.[A-Za-z_][A-Za-z0-9_]*$", "description": "A static method in menubar/Sources/, written Type.method."},
              "window": {"enum": ["open", "close", "reload"], "description": "Act on the declared window."}
            }
          },
          {"$ref": "#/definitions/namedOutlet"}
        ]
      }
    },
    "outletMark": {"type": "string", "enum": ["outlet"], "description": "The default outlet: where uses' fragments land."},
    "namedOutlet": {
      "type": "object",
      "required": ["outlet"],
      "additionalProperties": false,
      "properties": {"outlet": {"type": ["string", "null"], "pattern": "^[A-Za-z_][A-Za-z0-9_]*$", "description": "A named outlet; a use's fragment of that name lands here."}}
    }
  }
}
`

// templateLaunchAgentPattern also allows a value containing a ${param} hole,
// which a menubar.yaml's launchagent, a real launchd label, never holds.
const templateLaunchAgentPattern = `^([A-Za-z0-9][A-Za-z0-9._-]*|.*\$\{[A-Za-z_][A-Za-z0-9_]*\}.*)$`

// TemplateJSON is the schema for a template file. It is cut from JSON rather
// than written again, so a watch, state, rule or item means the same in both.
func TemplateJSON() string {
	var doc map[string]any
	if err := json.Unmarshal([]byte(body), &doc); err != nil {
		panic("schema: " + err.Error())
	}
	props, _ := doc["properties"].(map[string]any)
	defs, _ := doc["definitions"].(map[string]any)
	if props == nil || defs == nil {
		panic("schema: TemplateJSON: the schema has no properties or definitions")
	}

	watch := deepCopy(at(props, "watch"))
	launchagent, ok := at(watch, "additionalProperties", "properties", "launchagent").(map[string]any)
	if !ok {
		panic("schema: TemplateJSON: watch.additionalProperties.properties.launchagent is not an object")
	}
	launchagent["pattern"] = templateLaunchAgentPattern

	// A template's status rule is JSON()'s with when: required.
	statusRule, ok := deepCopy(at(props, "status", "items", "oneOf", 0)).(map[string]any)
	if !ok {
		panic("schema: TemplateJSON: status.items.oneOf.0 is not an object")
	}
	statusRule["required"] = []string{"when"}

	// menuItem's own "menu" field still $refs #/definitions/menu, so a nested
	// submenu may hold outlet marks even though a fragment's top level may not.
	menuItem, ok := deepCopy(at(defs, "menu", "items", "oneOf", 1)).(map[string]any)
	if !ok {
		panic("schema: TemplateJSON: definitions.menu.items.oneOf.1 is not an object")
	}
	defs["templateMenu"] = map[string]any{
		"type": "array",
		"items": map[string]any{
			"oneOf": []any{
				map[string]any{"type": "string", "enum": []string{"separator"}},
				menuItem,
			},
		},
	}

	outletNames := map[string]any{"pattern": "^[A-Za-z_][A-Za-z0-9_]*$"}
	tmpl := map[string]any{
		"$schema":              doc["$schema"],
		"title":                "perch template",
		"description":          "A template a menubar.yaml reaches under use:.",
		"type":                 "object",
		"additionalProperties": false,
		"definitions":          defs,
		"properties": map[string]any{
			"params": map[string]any{
				"type":                 "object",
				"description":          "Parameter names and their defaults; ~ makes one required.",
				"propertyNames":        map[string]any{"pattern": "^[A-Za-z_][A-Za-z0-9_]*$"},
				"additionalProperties": map[string]any{"type": []string{"string", "number", "boolean", "null"}},
			},
			"watch": watch,
			"state": at(props, "state"),
			"status": map[string]any{
				"type":                 "object",
				"description":          "Outlet names to status rules; default is the default outlet. Every rule needs when:.",
				"propertyNames":        outletNames,
				"additionalProperties": map[string]any{"type": "array", "items": statusRule},
			},
			"menu": map[string]any{
				"type":                 "object",
				"description":          "Outlet names to menu items; default is the default outlet.",
				"propertyNames":        outletNames,
				"additionalProperties": map[string]any{"$ref": "#/definitions/templateMenu"},
			},
		},
	}
	out, err := json.MarshalIndent(tmpl, "", "  ")
	if err != nil {
		panic("schema: " + err.Error())
	}
	return string(out) + "\n"
}

// at walks a decoded JSON document by key (string) or index (int) and panics,
// naming the path, if a segment is missing — so a fragment TemplateJSON reads
// fails loudly rather than emitting null.
func at(v any, path ...any) any {
	for i, seg := range path {
		switch key := seg.(type) {
		case string:
			m, ok := v.(map[string]any)
			if !ok {
				panic(fmt.Sprintf("schema: TemplateJSON: %v: not an object", path[:i+1]))
			}
			if v, ok = m[key]; !ok {
				panic(fmt.Sprintf("schema: TemplateJSON: %v: missing", path[:i+1]))
			}
		case int:
			l, ok := v.([]any)
			if !ok || key < 0 || key >= len(l) {
				panic(fmt.Sprintf("schema: TemplateJSON: %v: missing", path[:i+1]))
			}
			v = l[key]
		default:
			panic(fmt.Sprintf("schema: TemplateJSON: bad path segment %v (%T)", seg, seg))
		}
	}
	return v
}

// deepCopy lets TemplateJSON edit a fragment without changing JSON()'s.
func deepCopy(v any) any {
	b, err := json.Marshal(v)
	if err != nil {
		panic("schema: " + err.Error())
	}
	var out any
	if err := json.Unmarshal(b, &out); err != nil {
		panic("schema: " + err.Error())
	}
	return out
}
