// Package schema emits the JSON Schema an editor uses for completion and
// inline errors, via the yaml-language-server header in menubar.yaml.
package schema

// JSON is the schema for menubar.yaml. It mirrors what spec.Parse accepts;
// where the two could drift, spec.Parse is the authority.
func JSON() string { return body }

const body = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "menubar.yaml",
  "description": "A macOS menu bar app, generated by perch.",
  "type": "object",
  "required": ["app"],
  "additionalProperties": false,
  "properties": {
    "app": {
      "type": "object",
      "required": ["name", "id", "icon", "interval"],
      "additionalProperties": false,
      "properties": {
        "name": {"type": "string", "pattern": "^[^./\\\\][^/\\\\]*$", "description": "Bundle and executable name; one path component under ~/Applications."},
        "id": {"type": "string", "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]*$", "description": "Bundle identifier, e.g. dev.example.menubar."},
        "icon": {"description": "An SF Symbol name, or {asset: <name>} for a .png in menubar/Icons.", "oneOf": [{"type": "string"}, {"type": "object", "required": ["asset"], "additionalProperties": false, "properties": {"asset": {"type": "string", "pattern": "^[A-Za-z0-9_-]+$"}}}]},
        "interval": {"type": "string", "pattern": "^([0-9]+(\\.[0-9]+)?(ns|us|\u00b5s|ms|s|m|h))+$", "description": "Poll interval, e.g. 5s or 1m30s."}
      }
    },
    "watch": {
      "type": "object",
      "description": "Named sources, polled concurrently every interval.",
      "propertyNames": {"pattern": "^[A-Za-z_][A-Za-z0-9_]*$", "not": {"enum": ["it", "as", "break", "const", "continue", "else", "false", "for", "function", "if", "import", "in", "let", "loop", "namespace", "null", "package", "return", "true", "var", "void", "while"]}},
      "additionalProperties": {
        "type": "object",
        "additionalProperties": false,
        "oneOf": [
          {"required": ["run"]},
          {"required": ["http"]},
          {"required": ["exists"]}
        ],
        "properties": {
          "run": {"type": "array", "minItems": 1, "items": {"type": "string"}, "description": "argv, never a shell."},
          "http": {"type": "string", "description": "URL; .ok is a 2xx."},
          "exists": {"type": "string", "description": "Path; binds .ok only."},
          "json": {"type": "boolean", "description": "Decode the output into .data."},
          "shape": {"$ref": "#/definitions/shape"}
        }
      }
    },
    "state": {
      "type": "array",
      "description": "Named states, first match wins. The last takes no condition and is the fallback, so exactly one state always holds.",
      "items": {
        "type": "object",
        "minProperties": 1,
        "maxProperties": 1,
        "additionalProperties": {"type": ["string", "null"], "description": "CEL condition reaching this state; omit on the last one."},
        "propertyNames": {"pattern": "^[A-Za-z_][A-Za-z0-9_]*$", "not": {"enum": ["it"]}}
      }
    },
    "status": {
      "type": "array",
      "description": "First matching rule wins.",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "when": {"type": "string", "description": "CEL condition; omit to always match."},
          "icon": {"description": "An SF Symbol name, or {asset: <name>} for a .png in menubar/Icons.", "oneOf": [{"type": "string"}, {"type": "object", "required": ["asset"], "additionalProperties": false, "properties": {"asset": {"type": "string", "pattern": "^[A-Za-z0-9_-]+$"}}}]},
          "dim": {"type": "boolean"},
          "badge": {"type": "string", "description": "CEL expression shown beside the icon."}
        }
      }
    },
    "menu": {"$ref": "#/definitions/menu"}
  },
  "definitions": {
    "shape": {
      "description": "What a command prints: string, int, double, bool, any, objects, and [T].",
      "oneOf": [
        {"type": "string", "enum": ["string", "int", "double", "bool", "any"]},
        {"type": "array", "minItems": 1, "maxItems": 1, "items": {"$ref": "#/definitions/shape"}},
        {"type": "object", "propertyNames": {"pattern": "^[A-Za-z_][A-Za-z0-9_]*$"}, "additionalProperties": {"$ref": "#/definitions/shape"}}
      ]
    },
    "menu": {
      "type": "array",
      "items": {
        "oneOf": [
          {"type": "string", "enum": ["separator"]},
          {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "text": {"type": "string", "description": "Label; {{ }} holes are CEL."},
              "when": {"type": "string", "description": "CEL condition deciding whether the item appears."},
              "each": {"type": "string", "description": "CEL list expression; the element binds to it."},
              "menu": {"$ref": "#/definitions/menu"},
              "run": {"type": "array", "minItems": 1, "items": {"type": "string"}, "description": "argv, never a shell."},
              "open": {"type": "string", "description": "URL or path."},
              "post": {
                "type": "object",
                "required": ["url"],
                "additionalProperties": false,
                "properties": {"url": {"type": "string"}, "body": {}}
              },
              "quit": {"type": "boolean"}
            }
          }
        ]
      }
    }
  }
}
`
