// Package schema emits the JSON Schema an editor uses for completion and
// inline errors, via the yaml-language-server header in menubar.yaml.
package schema

import (
	"encoding/json"
	"fmt"
)

// JSON is the schema for menubar.yaml. It mirrors what spec.Parse accepts;
// where the two could drift, spec.Parse is the authority.
func JSON() string { return body }

const body = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "menubar.yaml",
  "description": "A macOS menu bar app, generated by perch.",
  "type": "object",
  "required": ["app"],
  "additionalProperties": false,
  "properties": {
    "app": {
      "type": "object",
      "required": ["name", "id", "icon", "interval"],
      "additionalProperties": false,
      "properties": {
        "name": {"type": "string", "pattern": "^[^./\\\\][^/\\\\]*$", "description": "Bundle and executable name; one path component under ~/Applications."},
        "id": {"type": "string", "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]*$", "description": "Bundle identifier, e.g. dev.example.menubar."},
        "icon": {"description": "An SF Symbol name, or {asset: <name>} for a .png in menubar/Icons.", "oneOf": [{"type": "string"}, {"type": "object", "required": ["asset"], "additionalProperties": false, "properties": {"asset": {"type": "string", "pattern": "^[A-Za-z0-9_-]+$"}}}]},
        "tint": {"$ref": "#/definitions/tint"},
        "interval": {"type": "string", "pattern": "^([0-9]+(\\.[0-9]+)?(ns|us|\u00b5s|ms|s|m|h))+$", "description": "Poll interval, e.g. 5s or 1m30s."},
        "sign": {"type": "string", "description": "Keychain code signing identity for the .app. Omit to sign ad-hoc."},
        "hotkey": {"type": "string", "pattern": "^(((cmd|opt|ctrl|shift)\\+)*f([1-9]|1[0-9]|20)|((cmd|opt|ctrl|shift)\\+)*(cmd|opt|ctrl)\\+((cmd|opt|ctrl|shift)\\+)*([a-z0-9]|space|return|tab|escape|delete|forwarddelete|left|right|up|down|home|end|pageup|pagedown|[-=;',./\u0060\\[\\]\\\\]))$", "description": "A shortcut that opens the menu from any app, e.g. cmd+shift+space: modifiers (cmd, opt, ctrl, shift) joined by + before one key, in lowercase. It needs cmd, opt or ctrl unless the key is f1 to f20."},
        "quit": {
          "type": "array",
          "description": "What quitting asks first. First matching rule wins; the last takes no when:.",
          "items": {
            "type": "object",
            "required": ["confirm"],
            "additionalProperties": false,
            "properties": {
              "when": {"type": "string", "description": "CEL condition; omit on the last rule."},
              "confirm": {"type": "string", "description": "The question."},
              "detail": {"type": "string", "description": "The smaller text under it."},
              "buttons": {
                "type": "array",
                "description": "Offered in order; the first is the default, Cancel is implicit and last.",
                "items": {
                  "type": "object",
                  "required": ["text"],
                  "additionalProperties": false,
                  "properties": {
                    "text": {"type": "string"},
                    "run": {"type": "array", "minItems": 1, "items": {"type": "string"}},
                    "open": {"type": "string"},
                    "post": {"type": "object", "required": ["url"], "additionalProperties": false, "properties": {"url": {"type": "string"}, "body": {}}},
                    "agent": {"type": "string", "pattern": "^([A-Za-z_][A-Za-z0-9_]*\\.){1,2}(start|stop|restart)$"},
                    "swift": {"type": "string", "pattern": "^[A-Za-z_][A-Za-z0-9_]*\\.[A-Za-z_][A-Za-z0-9_]*$"}
                  }
                }
              }
            }
          }
        }
      }
    },
    "watch": {
      "type": "object",
      "description": "Named sources, polled concurrently every interval.",
      "propertyNames": {"pattern": "^[A-Za-z_][A-Za-z0-9_]*$", "not": {"enum": ["it", "self", "query", "init", "Type", "Protocol", "as", "break", "const", "continue", "else", "false", "for", "function", "if", "import", "in", "let", "loop", "namespace", "null", "package", "return", "true", "var", "void", "while"]}},
      "additionalProperties": {
        "type": "object",
        "additionalProperties": false,
        "oneOf": [
          {"required": ["run"]},
          {"required": ["http"]},
          {"required": ["exists"]},
          {"required": ["launchagent"]}
        ],
        "properties": {
          "run": {"type": "array", "minItems": 1, "items": {"type": "string"}, "description": "argv, never a shell."},
          "http": {"type": "string", "description": "URL; .ok is a 2xx."},
          "exists": {"type": "string", "description": "Path; binds .ok only."},
          "launchagent": {"type": "string", "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]*$", "description": "A launchd label, e.g. dev.example.worker. Binds .installed, .loaded, .running, .pid, .label, .plist, .domain, .target."},
          "plist": {"type": "string", "description": "Where the LaunchAgent file is; defaults to ~/Library/LaunchAgents/<label>.plist. Needs launchagent."},
          "json": {"type": "boolean", "description": "Decode the output into .data."},
          "shape": {"$ref": "#/definitions/shape"}
        }
      }
    },
    "state": {
      "type": "array",
      "description": "Named states, first match wins. The last takes no condition and is the fallback, so exactly one state always holds.",
      "items": {
        "type": "object",
        "minProperties": 1,
        "maxProperties": 1,
        "additionalProperties": {"type": ["string", "null"], "description": "CEL condition reaching this state; omit on the last one."},
        "propertyNames": {"pattern": "^[A-Za-z_][A-Za-z0-9_]*$", "not": {"enum": ["it", "self", "query", "init", "Type", "Protocol", "as", "break", "const", "continue", "else", "false", "for", "function", "if", "import", "in", "let", "loop", "namespace", "null", "package", "return", "true", "var", "void", "while"]}}
      }
    },
    "use": {
      "type": "object",
      "description": "Named uses of templates. Each takes exactly one template, and its arguments.",
      "propertyNames": {"pattern": "^[A-Za-z_][A-Za-z0-9_]*$", "not": {"enum": ["it", "self", "query", "init", "Type", "Protocol", "as", "break", "const", "continue", "else", "false", "for", "function", "if", "import", "in", "let", "loop", "namespace", "null", "package", "return", "true", "var", "void", "while"]}},
      "additionalProperties": {
        "type": "object",
        "minProperties": 1,
        "maxProperties": 1,
        "additionalProperties": {"type": ["object", "null"], "additionalProperties": {"type": ["string", "number", "boolean"]}}
      }
    },
    "status": {
      "type": "array",
      "description": "First matching rule wins. An outlet item places the uses' status rules.",
      "items": {
        "oneOf": [
          {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "when": {"type": "string", "description": "CEL condition; omit to always match."},
              "icon": {"description": "An SF Symbol name, or {asset: <name>} for a .png in menubar/Icons.", "oneOf": [{"type": "string"}, {"type": "object", "required": ["asset"], "additionalProperties": false, "properties": {"asset": {"type": "string", "pattern": "^[A-Za-z0-9_-]+$"}}}]},
              "tint": {"$ref": "#/definitions/tint", "description": "Replaces app.tint while this rule holds."},
              "dim": {"type": "boolean"},
              "badge": {"type": "string", "description": "CEL expression shown beside the icon."}
            }
          },
          {"$ref": "#/definitions/outletMark"},
          {"$ref": "#/definitions/namedOutlet"}
        ]
      }
    },
    "window": {
      "type": "object",
      "description": "One WebKit window, opened from a menu item.",
      "required": ["url"],
      "additionalProperties": false,
      "properties": {
        "url": {"type": "string", "description": "The page the window loads."},
        "title": {"type": "string", "description": "Window title; defaults to app.name."},
        "size": {"type": "array", "minItems": 2, "maxItems": 2, "items": {"type": "integer", "minimum": 1}, "description": "[width, height] in points; defaults to [1024, 768]."},
        "zoom": {
          "type": "object",
          "description": "Page zoom bounds. Omit for no zoom controls.",
          "required": ["min", "max", "step"],
          "additionalProperties": false,
          "properties": {
            "min": {"type": "number", "exclusiveMinimum": 0},
            "max": {"type": "number", "exclusiveMinimum": 0},
            "step": {"type": "number", "exclusiveMinimum": 0}
          }
        }
      }
    },
    "menu": {"$ref": "#/definitions/menu"}
  },
  "definitions": {
    "tintColor": {
      "description": "#rrggbb, #rrggbbaa, or a macOS system color, which shifts between a light and a dark menu bar.",
      "oneOf": [
        {"type": "string", "pattern": "^#[0-9a-fA-F]{6}([0-9a-fA-F]{2})?$"},
        {"type": "string", "enum": ["red", "orange", "yellow", "green", "mint", "teal", "cyan", "blue", "indigo", "purple", "pink", "brown", "gray"]}
      ]
    },
    "tint": {
      "description": "A color on the status item, to tell this app from others. A color alone draws a dot.",
      "oneOf": [
        {"$ref": "#/definitions/tintColor"},
        {
          "type": "object",
          "required": ["color"],
          "additionalProperties": false,
          "properties": {
            "color": {"$ref": "#/definitions/tintColor"},
            "style": {"enum": ["dot", "glyph", "accent", "chip"], "description": "dot: a dot on one corner. glyph: the whole symbol. accent: the symbol's secondary layer. chip: a patch behind the icon. Default dot."},
            "size": {"enum": ["small", "medium", "large"], "description": "The dot's size. Default small."},
            "corner": {"enum": ["bottom-right", "bottom-left", "top-right", "top-left"], "description": "Where the dot sits. Default bottom-right."},
            "wrap": {"enum": ["icon", "all"], "description": "What a chip covers: the icon, or the icon and the badge. Default icon."},
            "menu": {"type": "boolean", "description": "Tint the dropdown's glass too, in the same color and opacity. Default false."},
            "opacity": {"type": ["number", "string"], "description": "The color's opacity from 0 to 1, or a CEL expression giving one. Replaces a #rrggbbaa alpha and the chip's default 0.35."}
          }
        }
      ]
    },
    "shape": {
      "description": "What a command prints: string, int, double, bool, any, objects, and [T].",
      "oneOf": [
        {"type": "string", "enum": ["string", "int", "double", "bool", "any"]},
        {"type": "array", "minItems": 1, "maxItems": 1, "items": {"$ref": "#/definitions/shape"}},
        {"type": "object", "propertyNames": {"pattern": "^[A-Za-z_][A-Za-z0-9_]*$", "not": {"enum": ["self", "init", "Type", "Protocol", "as", "break", "const", "continue", "else", "false", "for", "function", "if", "import", "in", "let", "loop", "namespace", "null", "package", "return", "true", "var", "void", "while"]}}, "additionalProperties": {"$ref": "#/definitions/shape"}}
      ]
    },
    "menu": {
      "type": "array",
      "items": {
        "oneOf": [
          {"type": "string", "enum": ["separator", "outlet"]},
          {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "text": {"type": "string", "description": "Label; {{ }} holes are CEL."},
              "field": {"type": "string", "description": "A search field; this is its placeholder. Enter fires the item's run, open, post or swift with the typed text bound as query. {{ }} holes are CEL."},
              "icon": {"description": "An SF Symbol name, or {asset: <name>} for a .png in menubar/Icons, drawn beside the label. {{ }} holes are CEL; a name that resolves to nothing draws no icon.", "oneOf": [{"type": "string"}, {"type": "object", "required": ["asset"], "additionalProperties": false, "properties": {"asset": {"type": "string", "pattern": "^([A-Za-z0-9_-]|\\{\\{[^}]*\\}\\})+$"}}}]},
              "when": {"type": "string", "description": "CEL condition deciding whether the item appears."},
              "each": {"type": "string", "description": "CEL list expression; the element binds to it."},
              "menu": {"$ref": "#/definitions/menu"},
              "run": {"type": "array", "minItems": 1, "items": {"type": "string"}, "description": "argv, never a shell."},
              "open": {"type": "string", "description": "URL or path."},
              "post": {
                "type": "object",
                "required": ["url"],
                "additionalProperties": false,
                "properties": {"url": {"type": "string"}, "body": {}}
              },
              "quit": {"type": "boolean"},
              "agent": {"type": "string", "pattern": "^([A-Za-z_][A-Za-z0-9_]*\\.){1,2}(start|stop|restart)$", "description": "<watch>, <use>.<watch> or self.<watch>, then .start, .stop or .restart."},
              "swift": {"type": "string", "pattern": "^[A-Za-z_][A-Za-z0-9_]*\\.[A-Za-z_][A-Za-z0-9_]*$", "description": "A static method in menubar/Sources/, written Type.method."},
              "window": {"enum": ["open", "close", "reload"], "description": "Act on the declared window."}
            }
          },
          {"$ref": "#/definitions/namedOutlet"}
        ]
      }
    },
    "outletMark": {"type": "string", "enum": ["outlet"], "description": "The default outlet: where uses' fragments land."},
    "namedOutlet": {
      "type": "object",
      "required": ["outlet"],
      "additionalProperties": false,
      "properties": {"outlet": {"type": ["string", "null"], "pattern": "^[A-Za-z_][A-Za-z0-9_]*$", "description": "A named outlet; a use's fragment of that name lands here."}}
    }
  }
}
`

// paramHole is a string holding a ${param}. A template's every scalar value is
// filled before it is parsed, so any of them may be one.
var paramHole = map[string]any{"type": "string", "pattern": `\$\{[A-Za-z_][A-Za-z0-9_]*\}`, "description": "A ${param} hole, filled before the template is parsed."}

// TemplateJSON is the schema for a template file. It is cut from JSON rather
// than written again, so a watch, state, rule or item means the same in both.
func TemplateJSON() string {
	var doc map[string]any
	if err := json.Unmarshal([]byte(body), &doc); err != nil {
		panic("schema: " + err.Error())
	}
	props, _ := doc["properties"].(map[string]any)
	defs, _ := doc["definitions"].(map[string]any)
	if props == nil || defs == nil {
		panic("schema: TemplateJSON: the schema has no properties or definitions")
	}

	statusRule, ok := deepCopy(at(props, "status", "items", "oneOf", 0)).(map[string]any)
	if !ok {
		panic("schema: TemplateJSON: status.items.oneOf.0 is not an object")
	}
	statusRule["required"] = []string{"when"}

	menuItem, ok := deepCopy(at(defs, "menu", "items", "oneOf", 1)).(map[string]any)
	if !ok {
		panic("schema: TemplateJSON: definitions.menu.items.oneOf.1 is not an object")
	}
	at(menuItem, "properties").(map[string]any)["menu"] = map[string]any{"$ref": "#/definitions/templateMenu"}
	defs["templateMenu"] = map[string]any{
		"type": "array",
		"items": map[string]any{
			"oneOf": []any{
				map[string]any{"type": "string", "enum": []string{"separator"}},
				menuItem,
			},
		},
	}

	outletNames := map[string]any{"pattern": "^[A-Za-z_][A-Za-z0-9_]*$"}
	tmpl := map[string]any{
		"$schema":              doc["$schema"],
		"title":                "perch template",
		"description":          "A template a menubar.yaml reaches under use:.",
		"type":                 "object",
		"additionalProperties": false,
		"definitions":          defs,
		"properties": map[string]any{
			"params": map[string]any{
				"type":                 "object",
				"description":          "Parameter names and their defaults; ~ makes one required.",
				"propertyNames":        map[string]any{"pattern": "^[A-Za-z_][A-Za-z0-9_]*$"},
				"additionalProperties": map[string]any{"type": []string{"string", "number", "boolean", "null"}},
			},
			"watch": at(props, "watch"),
			"state": at(props, "state"),
			"status": map[string]any{
				"type":                 "object",
				"description":          "Outlet names to status rules; default is the default outlet. Every rule needs when:.",
				"propertyNames":        outletNames,
				"additionalProperties": map[string]any{"type": "array", "items": statusRule},
			},
			"menu": map[string]any{
				"type":                 "object",
				"description":          "Outlet names to menu items; default is the default outlet.",
				"propertyNames":        outletNames,
				"additionalProperties": map[string]any{"$ref": "#/definitions/templateMenu"},
			},
		},
	}
	for _, name := range []string{"watch", "state", "status", "menu"} {
		acceptParamsWithin(at(tmpl, "properties", name).(map[string]any))
	}
	acceptParamsWithin(map[string]any{"definitions": defs})
	defs["param"] = paramHole
	out, err := json.MarshalIndent(tmpl, "", "  ")
	if err != nil {
		panic("schema: " + err.Error())
	}
	return string(out) + "\n"
}

// acceptParams returns schema s, widened to take a paramHole wherever it would
// refuse one. Keys are never filled, so propertyNames stay as they are.
func acceptParams(s any) any {
	m, ok := s.(map[string]any)
	if !ok {
		return s
	}
	acceptParamsWithin(m)
	if !refusesHole(m) {
		return m
	}
	return map[string]any{"description": m["description"], "anyOf": []any{m, map[string]any{"$ref": "#/definitions/param"}}}
}

// acceptParamsWithin widens what s holds but not s itself. A oneOf's branches
// are widened only within, since two widened branches would both match a hole.
func acceptParamsWithin(s map[string]any) {
	for _, key := range []string{"properties", "definitions"} {
		if m, ok := s[key].(map[string]any); ok {
			for name, sub := range m {
				m[name] = acceptParams(sub)
			}
		}
	}
	for _, key := range []string{"items", "additionalProperties"} {
		if _, ok := s[key].(map[string]any); ok {
			s[key] = acceptParams(s[key])
		}
	}
	for _, key := range []string{"oneOf", "anyOf"} {
		branches, _ := s[key].([]any)
		for _, b := range branches {
			if m, ok := b.(map[string]any); ok {
				acceptParamsWithin(m)
			}
		}
	}
}

// refusesHole reports whether a scalar schema refuses a string like "${x}".
func refusesHole(s map[string]any) bool {
	if _, ok := s["enum"]; ok {
		return true
	}
	if _, ok := s["pattern"]; ok {
		return true
	}
	if branches, ok := s["oneOf"].([]any); ok {
		for _, b := range branches {
			if m, ok := b.(map[string]any); ok && refusesHole(m) {
				return true
			}
		}
	}
	var types []any
	switch t := s["type"].(type) {
	case string:
		types = []any{t}
	case []any:
		types = t
	}
	if len(types) == 0 {
		return false
	}
	for _, t := range types {
		if t == "string" || t == "object" || t == "array" {
			return false
		}
	}
	return true
}

// at walks a decoded JSON document by key (string) or index (int) and panics,
// naming the path, if a segment is missing — so a fragment TemplateJSON reads
// fails loudly rather than emitting null.
func at(v any, path ...any) any {
	for i, seg := range path {
		switch key := seg.(type) {
		case string:
			m, ok := v.(map[string]any)
			if !ok {
				panic(fmt.Sprintf("schema: TemplateJSON: %v: not an object", path[:i+1]))
			}
			if v, ok = m[key]; !ok {
				panic(fmt.Sprintf("schema: TemplateJSON: %v: missing", path[:i+1]))
			}
		case int:
			l, ok := v.([]any)
			if !ok || key < 0 || key >= len(l) {
				panic(fmt.Sprintf("schema: TemplateJSON: %v: missing", path[:i+1]))
			}
			v = l[key]
		default:
			panic(fmt.Sprintf("schema: TemplateJSON: bad path segment %v (%T)", seg, seg))
		}
	}
	return v
}

// deepCopy lets TemplateJSON edit a fragment without changing JSON()'s.
func deepCopy(v any) any {
	b, err := json.Marshal(v)
	if err != nil {
		panic("schema: " + err.Error())
	}
	var out any
	if err := json.Unmarshal(b, &out); err != nil {
		panic("schema: " + err.Error())
	}
	return out
}
