// Generated by perch from menubar.yaml. Regenerating overwrites this file.

import AppKit
import Foundation

struct ServerResult {
    var ok = false
    var status = 0
    var out = ""
    var data: JSONValue = JSONValue.null
}

struct AgentResult {
    var ok = false
    var code = -1
    var out = ""
    var err = ""
}

struct PlistResult {
    var ok = false
}

struct Results {
    var server = ServerResult()
    var agent = AgentResult()
    var plist = PlistResult()
}

final class Controller: NSObject, NSApplicationDelegate, NSMenuDelegate {
    private let statusItem = NSStatusBar.system.statusItem(withLength: NSStatusItem.variableLength)
    private var results = Results()
    private var timer: Timer?

    override init() {
        super.init()
        let menu = NSMenu()
        menu.delegate = self
        statusItem.menu = menu
        refresh()
        poll()
        timer = Timer.scheduledTimer(withTimeInterval: 10.0, repeats: true) { [weak self] _ in
            self?.poll()
        }
    }

    func poll() {
        let group = DispatchGroup()
        let sync = DispatchQueue(label: "dev.brainhouse.menubar.results")
        var next = Results()

        group.enter()
        DispatchQueue.global(qos: .utility).async {
            var r = ServerResult()
            let o = Watcher.http("http://127.0.0.1:8765/api/health")
            r.ok = o.ok
            r.status = o.status
            r.out = o.out
            r.data = JSONValue.parse(o.out)
            sync.async {
                next.server = r
                group.leave()
            }
        }

        group.enter()
        DispatchQueue.global(qos: .utility).async {
            var r = AgentResult()
            let o = Watcher.run(["launchctl", "print", "gui/501/dev.brainhouse"])
            r.ok = o.ok
            r.code = o.code
            r.out = o.out
            r.err = o.err
            sync.async {
                next.agent = r
                group.leave()
            }
        }

        group.enter()
        DispatchQueue.global(qos: .utility).async {
            var r = PlistResult()
            r.ok = Watcher.exists("~/Library/LaunchAgents/dev.brainhouse.plist")
            sync.async {
                next.plist = r
                group.leave()
            }
        }

        group.notify(queue: .main) { [weak self] in
            guard let self else { return }
            self.results = sync.sync { next }
            self.refresh()
            if let menu = self.statusItem.menu, menu.numberOfItems > 0 { self.menuNeedsUpdate(menu) }
        }
    }

    func refresh() {
        guard let button = statusItem.button else { return }
        var icon = MenuIcon.symbol("brain")
        var dim = false
        var badge = ""
        if !(self.results.plist.ok) {
            icon = MenuIcon.symbol("circle.dashed")
        } else if !(self.results.server.ok) {
            icon = MenuIcon.asset("alarm")
            dim = true
        } else {
            badge = String(self.results.server.data["sessions"].size)
        }
        button.image = icon.image()
        button.appearsDisabled = dim
        button.title = badge.isEmpty ? "" : " " + badge
    }

    func menuNeedsUpdate(_ menu: NSMenu) {
        menu.removeAllItems()
        if self.results.server.ok {
            menu.addItem(NSMenuItem(title: "\(String(self.results.server.data["sessions"].size)) sessions", action: nil, keyEquivalent: ""))
        }
        if !(self.results.server.ok) {
            menu.addItem(NSMenuItem(title: "not running", action: nil, keyEquivalent: ""))
        }
        menu.addItem(NSMenuItem.separator())
        menu.addItem(ActionItem(title: "Open") {
            Act.open("http://127.0.0.1:8765")
        })
        if self.results.agent.ok {
            menu.addItem(ActionItem(title: "Restart") { [weak self] in
                guard let self else { return }
                Act.run(["launchctl", "kickstart", "-k", "gui/501/dev.brainhouse"]) { self.poll() }
            })
        }
        menu.addItem(ActionItem(title: "Ping") { [weak self] in
            guard let self else { return }
            Act.post("http://127.0.0.1:8765/api/ping", body: "{\"source\":\"menubar\"}") { self.poll() }
        })
        menu.addItem(NSMenuItem.separator())
        menu.addItem(ActionItem(title: "Quit") {
            NSApp.terminate(nil)
        })
    }
}

let app = NSApplication.shared
app.setActivationPolicy(.accessory)
let controller = Controller()
app.delegate = controller
app.run()
