// Generated by perch from menubar.yaml. Regenerating overwrites this file.

import Foundation

struct ServerResult {
    var ok = false
    var status = 0
    var out = ""
    var data: JSONValue = JSONValue.null
}

struct AgentResult {
    var ok = false
    var code = -1
    var out = ""
    var err = ""
}

struct PlistResult {
    var ok = false
}

struct Results {
    var server = ServerResult()
    var agent = AgentResult()
    var plist = PlistResult()
}

extension ServerResult {
    init(_ o: HTTPOutcome) {
        self.init()
        ok = o.ok
        status = o.status
        out = o.out
        data = JSONValue.parse(o.out)
    }
}

extension AgentResult {
    init(_ o: RunOutcome) {
        self.init()
        ok = o.ok
        code = o.code
        out = o.out
        err = o.err
    }
}

extension PlistResult {
    init(exists: Bool) {
        self.init()
        ok = exists
    }
}

func renderFace(_ results: Results) -> Face {
    var face = Face(icon: MenuIcon.symbol("brain"))
    if !(results.plist.ok) {
        face.icon = MenuIcon.symbol("circle.dashed")
    } else if !(results.server.ok) {
        face.icon = MenuIcon.asset("alarm")
        face.dim = true
    } else {
        face.badge = String(results.server.data["sessions"].size)
    }
    return face
}

func renderMenu(_ results: Results) -> [MenuNode] {
    var menu: [MenuNode] = []
    if results.server.ok {
        menu.append(.item("\(String(results.server.data["sessions"].size)) sessions", nil))
    }
    if !(results.server.ok) {
        menu.append(.item("not running", nil))
    }
    menu.append(.separator)
    menu.append(.item("Open", .open("http://127.0.0.1:8765")))
    if results.agent.ok {
        menu.append(.item("Restart", .run(["launchctl", "kickstart", "-k", "gui/501/dev.brainhouse"])))
    }
    menu.append(.item("Ping", .post(url: "http://127.0.0.1:8765/api/ping", body: "{\"source\":\"menubar\"}")))
    menu.append(.separator)
    menu.append(.item("Quit", .quit))
    return menu
}
