// Generated by perch from menubar.yaml. Regenerating overwrites this file.

import Foundation

struct SvcResult {
    var installed = false
    var loaded = false
    var running = false
    var pid = 0
    var label = ""
    var plist = ""
    var domain = ""
    var target = ""
}

struct Results {
    var svc = SvcResult()
}

extension SvcResult {
    init(_ o: LaunchAgentOutcome) {
        self.init()
        installed = o.installed
        loaded = o.loaded
        running = o.running
        pid = o.pid
        label = o.label
        plist = o.plist
        domain = Launchd.domain
        target = Launchd.target(o.label)
    }
}

func renderFace(_ results: Results) -> Face {
    let face = Face(icon: MenuIcon.symbol("gear"))
    return face
}

func renderMenu(_ results: Results) -> [MenuNode] {
    var menu: [MenuNode] = []
    menu.append(.item("Quit", .quit))
    return tidy(menu)
}

func renderQuit(_ results: Results) -> QuitPrompt? {
    if results.svc.loaded {
        return QuitPrompt(
            message: "Quit w?",
            detail: "The server is running as a launchd service.",
            buttons: [
                QuitChoice(text: "Quit Both", action: .agent(label: "dev.example.svc", plist: "~/Library/LaunchAgents/dev.example.svc.plist", verb: .stop)),
                QuitChoice(text: "Quit Helper Only", action: nil),
            ])
    }
    return QuitPrompt(
        message: "Quit w?",
        detail: "The server keeps running.",
        buttons: [])
}
