// Generated by perch from menubar.yaml. Regenerating overwrites this file.

import AppKit
import Foundation

final class Controller: NSObject, NSApplicationDelegate, NSMenuDelegate, WindowActions, NSMenuItemValidation {
    private let statusItem = NSStatusBar.system.statusItem(withLength: NSStatusItem.variableLength)
    fileprivate var results = Results()
    private var timer: Timer?

    private let window = WebWindow(
        url: "http://localhost:4747/",
        title: "dash",
        width: 1280, height: 860,
        zoom: ZoomConfig(min: 0.5, max: 2.0, step: 0.1),
        autosaveName: "WWindow")
    private var mirror: MenuMirror?

    override init() {
        super.init()
        let menu = NSMenu()
        menu.delegate = self
        statusItem.menu = menu
        NSWorkspace.shared.notificationCenter.addObserver(
            forName: NSWorkspace.didActivateApplicationNotification, object: nil, queue: .main
            ) { [weak self] _ in self?.refresh() }
        refresh()
        poll()
        timer = Timer.scheduledTimer(withTimeInterval: 5.0, repeats: true) { [weak self] _ in
            self?.poll()
        }
        setUpWindow()
    }

    fileprivate func poll() {
        refresh()
    }

    func refresh() {
        guard let button = statusItem.button else { return }
        Draw.face(renderFace(results), on: button)
    }

    func menuNeedsUpdate(_ menu: NSMenu) {
        Draw.menu(renderMenu(results), into: menu) { [weak self] in self?.poll() }
    }
    private func act(_ verb: WindowVerb) {
        switch verb {
        case .open: window.show()
        case .close: window.hide()
        case .reload: window.load()
        }
    }

    private func setDockPresence(_ visible: Bool) {
        if visible {
            NSApp.setActivationPolicy(.regular)
        } else {
            NSApp.setActivationPolicy(.accessory)
            NSApp.deactivate()
        }
    }

    func closeWindow() { window.hide() }
    func reloadWindow() { window.load() }
    func zoomIn() { window.zoomIn() }
    func zoomOut() { window.zoomOut() }
    func actualSize() { window.actualSize() }
    func requestQuit() { NSApp.terminate(nil) }

    func applicationShouldHandleReopen(_ sender: NSApplication, hasVisibleWindows: Bool) -> Bool {
        window.show()
        return true
    }

    func validateMenuItem(_ menuItem: NSMenuItem) -> Bool {
        switch menuItem.action {
        case #selector(closeWindow), #selector(reloadWindow),
             #selector(zoomIn), #selector(zoomOut), #selector(actualSize):
            return window.isPresented
        default:
            return true
        }
    }

    private func setUpWindow() {
        window.onVisibilityChange = { [weak self] visible in self?.setDockPresence(visible) }
        Windows.handler = { [weak self] verb in self?.act(verb) }
        let mirror = MenuMirror(
            nodes: { [weak self] in self.map { renderMenu($0.results) } ?? [] },
            repoll: { [weak self] in self?.poll() })
        self.mirror = mirror
        MainMenu.install(appName: "w", canZoom: window.canZoom, mirror: mirror, target: self)
    }

}

let app = NSApplication.shared
app.setActivationPolicy(.accessory)
let controller = Controller()
app.delegate = controller
app.run()
