// Package swiftappkit emits a macOS status-bar app in Swift from a Spec.
package swiftappkit

import (
	_ "embed"
	"fmt"
	"strings"

	"github.com/orochi235/perch/internal/backend"
	"github.com/orochi235/perch/internal/celswift"
	"github.com/orochi235/perch/internal/spec"
)

//go:embed runtime/Runtime.swift
var runtimeSwift []byte

const header = "// Generated by perch from menubar.yaml. Regenerating overwrites this file.\n"

// Backend is the only backend perch ships.
type Backend struct{}

func New() *Backend { return &Backend{} }

func (*Backend) Name() string { return "swift-appkit" }

// Emit renders the whole generated directory. Nothing outside it is written.
func (*Backend) Emit(s *spec.Spec) ([]backend.File, error) {
	files := []backend.File{{Name: "Runtime.swift", Body: runtimeSwift}}

	n := nameStructs(s)
	if shapes := emitShapes(s, n); shapes != "" {
		files = append(files, backend.File{Name: "Shapes.swift", Body: []byte(shapes)})
	}
	main, err := emitMain(s, n)
	if err != nil {
		return nil, err
	}
	files = append(files, backend.File{Name: "main.swift", Body: []byte(main)})
	return files, nil
}

// buf writes indented Swift.
type buf struct {
	sb    strings.Builder
	depth int
}

func (b *buf) line(format string, args ...any) {
	if format != "" {
		b.sb.WriteString(strings.Repeat("    ", b.depth))
		fmt.Fprintf(&b.sb, format, args...)
	}
	b.sb.WriteByte('\n')
}

// raw appends already-indented source, for a block rendered separately.
func (b *buf) raw(s string) { b.sb.WriteString(s) }

func (b *buf) in()  { b.depth++ }
func (b *buf) out() { b.depth-- }

func (b *buf) String() string { return b.sb.String() }

var swiftKeywords = map[string]bool{
	"associatedtype": true, "class": true, "deinit": true, "enum": true, "extension": true,
	"fileprivate": true, "func": true, "import": true, "init": true, "inout": true,
	"internal": true, "let": true, "operator": true, "private": true, "protocol": true,
	"public": true, "rethrows": true, "static": true, "struct": true, "subscript": true,
	"typealias": true, "var": true, "break": true, "case": true, "continue": true,
	"default": true, "defer": true, "do": true, "else": true, "fallthrough": true,
	"for": true, "guard": true, "if": true, "in": true, "repeat": true, "return": true,
	"switch": true, "where": true, "while": true, "as": true, "catch": true, "false": true,
	"is": true, "nil": true, "super": true, "self": true, "throw": true, "throws": true,
	"true": true, "try": true, "precedencegroup": true, "Any": true, "Self": true,
	"Protocol": true, "Type": true,
}

// decl escapes a name for a Swift declaration site. Member access does not need
// this: x.default parses, while var default: Int does not.
func decl(name string) string {
	if swiftKeywords[name] {
		return "`" + name + "`"
	}
	return name
}

func exported(name string) string {
	parts := strings.FieldsFunc(name, func(r rune) bool { return r == '-' || r == '_' || r == '.' })
	var sb strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		sb.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return sb.String()
}

// env is the lowering environment for emitted code: watches are reached through
// the results record, so an expression never needs a local the code might not use.
func env(s *spec.Spec) *celswift.Env {
	return celswift.NewEnv(s.Watches).Prefixed("self.results.")
}
